// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudfront"
	mock "github.com/stretchr/testify/mock"
)

// NewCloudFrontClientPort creates a new instance of CloudFrontClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudFrontClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudFrontClientPort {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &CloudFrontClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// CloudFrontClientPort is an autogenerated mock type for the CloudFrontClientPort type
type CloudFrontClientPort struct {
	mock.Mock
}

type CloudFrontClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *CloudFrontClientPort) EXPECT() *CloudFrontClientPort_Expecter {
	return &CloudFrontClientPort_Expecter{mock: &_m.Mock}
}

// CreateDistribution provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) CreateDistribution(ctx context.Context, input *cloudfront.CreateDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateDistributionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateDistribution")
	}

	var r0 *cloudfront.CreateDistributionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateDistributionInput, ...func(*cloudfront.Options)) (*cloudfront.CreateDistributionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateDistributionInput, ...func(*cloudfront.Options)) *cloudfront.CreateDistributionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.CreateDistributionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.CreateDistributionInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_CreateDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDistribution'
type CloudFrontClientPort_CreateDistribution_Call struct {
	*mock.Call
}

// CreateDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.CreateDistributionInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) CreateDistribution(ctx any, input any, opts ...any) *CloudFrontClientPort_CreateDistribution_Call {
	return &CloudFrontClientPort_CreateDistribution_Call{Call: _e.mock.On("CreateDistribution",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_CreateDistribution_Call) Run(run func(ctx context.Context, input *cloudfront.CreateDistributionInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_CreateDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.CreateDistributionInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.CreateDistributionInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_CreateDistribution_Call) Return(createDistributionOutput *cloudfront.CreateDistributionOutput, err error) *CloudFrontClientPort_CreateDistribution_Call {
	_c.Call.Return(createDistributionOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_CreateDistribution_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.CreateDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateDistributionOutput, error)) *CloudFrontClientPort_CreateDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvalidation provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) CreateInvalidation(ctx context.Context, input *cloudfront.CreateInvalidationInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateInvalidationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateInvalidation")
	}

	var r0 *cloudfront.CreateInvalidationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateInvalidationInput, ...func(*cloudfront.Options)) (*cloudfront.CreateInvalidationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateInvalidationInput, ...func(*cloudfront.Options)) *cloudfront.CreateInvalidationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.CreateInvalidationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.CreateInvalidationInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_CreateInvalidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvalidation'
type CloudFrontClientPort_CreateInvalidation_Call struct {
	*mock.Call
}

// CreateInvalidation is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.CreateInvalidationInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) CreateInvalidation(ctx any, input any, opts ...any) *CloudFrontClientPort_CreateInvalidation_Call {
	return &CloudFrontClientPort_CreateInvalidation_Call{Call: _e.mock.On("CreateInvalidation",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_CreateInvalidation_Call) Run(run func(ctx context.Context, input *cloudfront.CreateInvalidationInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_CreateInvalidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.CreateInvalidationInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.CreateInvalidationInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_CreateInvalidation_Call) Return(createInvalidationOutput *cloudfront.CreateInvalidationOutput, err error) *CloudFrontClientPort_CreateInvalidation_Call {
	_c.Call.Return(createInvalidationOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_CreateInvalidation_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.CreateInvalidationInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateInvalidationOutput, error)) *CloudFrontClientPort_CreateInvalidation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOriginAccessControl provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) CreateOriginAccessControl(ctx context.Context, input *cloudfront.CreateOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateOriginAccessControlOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateOriginAccessControl")
	}

	var r0 *cloudfront.CreateOriginAccessControlOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateOriginAccessControlInput, ...func(*cloudfront.Options)) (*cloudfront.CreateOriginAccessControlOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.CreateOriginAccessControlInput, ...func(*cloudfront.Options)) *cloudfront.CreateOriginAccessControlOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.CreateOriginAccessControlOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.CreateOriginAccessControlInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_CreateOriginAccessControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOriginAccessControl'
type CloudFrontClientPort_CreateOriginAccessControl_Call struct {
	*mock.Call
}

// CreateOriginAccessControl is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.CreateOriginAccessControlInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) CreateOriginAccessControl(ctx any, input any, opts ...any) *CloudFrontClientPort_CreateOriginAccessControl_Call {
	return &CloudFrontClientPort_CreateOriginAccessControl_Call{Call: _e.mock.On("CreateOriginAccessControl",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_CreateOriginAccessControl_Call) Run(run func(ctx context.Context, input *cloudfront.CreateOriginAccessControlInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_CreateOriginAccessControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.CreateOriginAccessControlInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.CreateOriginAccessControlInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_CreateOriginAccessControl_Call) Return(createOriginAccessControlOutput *cloudfront.CreateOriginAccessControlOutput, err error) *CloudFrontClientPort_CreateOriginAccessControl_Call {
	_c.Call.Return(createOriginAccessControlOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_CreateOriginAccessControl_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.CreateOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.CreateOriginAccessControlOutput, error)) *CloudFrontClientPort_CreateOriginAccessControl_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDistribution provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) DeleteDistribution(ctx context.Context, input *cloudfront.DeleteDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.DeleteDistributionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteDistribution")
	}

	var r0 *cloudfront.DeleteDistributionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.DeleteDistributionInput, ...func(*cloudfront.Options)) (*cloudfront.DeleteDistributionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.DeleteDistributionInput, ...func(*cloudfront.Options)) *cloudfront.DeleteDistributionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.DeleteDistributionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.DeleteDistributionInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_DeleteDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDistribution'
type CloudFrontClientPort_DeleteDistribution_Call struct {
	*mock.Call
}

// DeleteDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.DeleteDistributionInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) DeleteDistribution(ctx any, input any, opts ...any) *CloudFrontClientPort_DeleteDistribution_Call {
	return &CloudFrontClientPort_DeleteDistribution_Call{Call: _e.mock.On("DeleteDistribution",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_DeleteDistribution_Call) Run(run func(ctx context.Context, input *cloudfront.DeleteDistributionInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_DeleteDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.DeleteDistributionInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.DeleteDistributionInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_DeleteDistribution_Call) Return(deleteDistributionOutput *cloudfront.DeleteDistributionOutput, err error) *CloudFrontClientPort_DeleteDistribution_Call {
	_c.Call.Return(deleteDistributionOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_DeleteDistribution_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.DeleteDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.DeleteDistributionOutput, error)) *CloudFrontClientPort_DeleteDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOriginAccessControl provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) DeleteOriginAccessControl(ctx context.Context, input *cloudfront.DeleteOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.DeleteOriginAccessControlOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteOriginAccessControl")
	}

	var r0 *cloudfront.DeleteOriginAccessControlOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.DeleteOriginAccessControlInput, ...func(*cloudfront.Options)) (*cloudfront.DeleteOriginAccessControlOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.DeleteOriginAccessControlInput, ...func(*cloudfront.Options)) *cloudfront.DeleteOriginAccessControlOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.DeleteOriginAccessControlOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.DeleteOriginAccessControlInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_DeleteOriginAccessControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOriginAccessControl'
type CloudFrontClientPort_DeleteOriginAccessControl_Call struct {
	*mock.Call
}

// DeleteOriginAccessControl is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.DeleteOriginAccessControlInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) DeleteOriginAccessControl(ctx any, input any, opts ...any) *CloudFrontClientPort_DeleteOriginAccessControl_Call {
	return &CloudFrontClientPort_DeleteOriginAccessControl_Call{Call: _e.mock.On("DeleteOriginAccessControl",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_DeleteOriginAccessControl_Call) Run(run func(ctx context.Context, input *cloudfront.DeleteOriginAccessControlInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_DeleteOriginAccessControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.DeleteOriginAccessControlInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.DeleteOriginAccessControlInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_DeleteOriginAccessControl_Call) Return(deleteOriginAccessControlOutput *cloudfront.DeleteOriginAccessControlOutput, err error) *CloudFrontClientPort_DeleteOriginAccessControl_Call {
	_c.Call.Return(deleteOriginAccessControlOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_DeleteOriginAccessControl_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.DeleteOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.DeleteOriginAccessControlOutput, error)) *CloudFrontClientPort_DeleteOriginAccessControl_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistribution provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) GetDistribution(ctx context.Context, input *cloudfront.GetDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetDistributionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDistribution")
	}

	var r0 *cloudfront.GetDistributionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetDistributionInput, ...func(*cloudfront.Options)) (*cloudfront.GetDistributionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetDistributionInput, ...func(*cloudfront.Options)) *cloudfront.GetDistributionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.GetDistributionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.GetDistributionInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_GetDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistribution'
type CloudFrontClientPort_GetDistribution_Call struct {
	*mock.Call
}

// GetDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.GetDistributionInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) GetDistribution(ctx any, input any, opts ...any) *CloudFrontClientPort_GetDistribution_Call {
	return &CloudFrontClientPort_GetDistribution_Call{Call: _e.mock.On("GetDistribution",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_GetDistribution_Call) Run(run func(ctx context.Context, input *cloudfront.GetDistributionInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_GetDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.GetDistributionInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.GetDistributionInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_GetDistribution_Call) Return(getDistributionOutput *cloudfront.GetDistributionOutput, err error) *CloudFrontClientPort_GetDistribution_Call {
	_c.Call.Return(getDistributionOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_GetDistribution_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.GetDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetDistributionOutput, error)) *CloudFrontClientPort_GetDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistributionConfig provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) GetDistributionConfig(ctx context.Context, input *cloudfront.GetDistributionConfigInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetDistributionConfigOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDistributionConfig")
	}

	var r0 *cloudfront.GetDistributionConfigOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetDistributionConfigInput, ...func(*cloudfront.Options)) (*cloudfront.GetDistributionConfigOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetDistributionConfigInput, ...func(*cloudfront.Options)) *cloudfront.GetDistributionConfigOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.GetDistributionConfigOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.GetDistributionConfigInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_GetDistributionConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistributionConfig'
type CloudFrontClientPort_GetDistributionConfig_Call struct {
	*mock.Call
}

// GetDistributionConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.GetDistributionConfigInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) GetDistributionConfig(ctx any, input any, opts ...any) *CloudFrontClientPort_GetDistributionConfig_Call {
	return &CloudFrontClientPort_GetDistributionConfig_Call{Call: _e.mock.On("GetDistributionConfig",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_GetDistributionConfig_Call) Run(run func(ctx context.Context, input *cloudfront.GetDistributionConfigInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_GetDistributionConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.GetDistributionConfigInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.GetDistributionConfigInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_GetDistributionConfig_Call) Return(getDistributionConfigOutput *cloudfront.GetDistributionConfigOutput, err error) *CloudFrontClientPort_GetDistributionConfig_Call {
	_c.Call.Return(getDistributionConfigOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_GetDistributionConfig_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.GetDistributionConfigInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetDistributionConfigOutput, error)) *CloudFrontClientPort_GetDistributionConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginAccessControl provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) GetOriginAccessControl(ctx context.Context, input *cloudfront.GetOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetOriginAccessControlOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetOriginAccessControl")
	}

	var r0 *cloudfront.GetOriginAccessControlOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetOriginAccessControlInput, ...func(*cloudfront.Options)) (*cloudfront.GetOriginAccessControlOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.GetOriginAccessControlInput, ...func(*cloudfront.Options)) *cloudfront.GetOriginAccessControlOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.GetOriginAccessControlOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.GetOriginAccessControlInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_GetOriginAccessControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginAccessControl'
type CloudFrontClientPort_GetOriginAccessControl_Call struct {
	*mock.Call
}

// GetOriginAccessControl is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.GetOriginAccessControlInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) GetOriginAccessControl(ctx any, input any, opts ...any) *CloudFrontClientPort_GetOriginAccessControl_Call {
	return &CloudFrontClientPort_GetOriginAccessControl_Call{Call: _e.mock.On("GetOriginAccessControl",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_GetOriginAccessControl_Call) Run(run func(ctx context.Context, input *cloudfront.GetOriginAccessControlInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_GetOriginAccessControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.GetOriginAccessControlInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.GetOriginAccessControlInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_GetOriginAccessControl_Call) Return(getOriginAccessControlOutput *cloudfront.GetOriginAccessControlOutput, err error) *CloudFrontClientPort_GetOriginAccessControl_Call {
	_c.Call.Return(getOriginAccessControlOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_GetOriginAccessControl_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.GetOriginAccessControlInput, opts ...func(*cloudfront.Options)) (*cloudfront.GetOriginAccessControlOutput, error)) *CloudFrontClientPort_GetOriginAccessControl_Call {
	_c.Call.Return(run)
	return _c
}

// ListDistributions provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) ListDistributions(ctx context.Context, input *cloudfront.ListDistributionsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListDistributions")
	}

	var r0 *cloudfront.ListDistributionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListDistributionsInput, ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListDistributionsInput, ...func(*cloudfront.Options)) *cloudfront.ListDistributionsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.ListDistributionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.ListDistributionsInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_ListDistributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistributions'
type CloudFrontClientPort_ListDistributions_Call struct {
	*mock.Call
}

// ListDistributions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.ListDistributionsInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) ListDistributions(ctx any, input any, opts ...any) *CloudFrontClientPort_ListDistributions_Call {
	return &CloudFrontClientPort_ListDistributions_Call{Call: _e.mock.On("ListDistributions",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_ListDistributions_Call) Run(run func(ctx context.Context, input *cloudfront.ListDistributionsInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_ListDistributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.ListDistributionsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.ListDistributionsInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_ListDistributions_Call) Return(listDistributionsOutput *cloudfront.ListDistributionsOutput, err error) *CloudFrontClientPort_ListDistributions_Call {
	_c.Call.Return(listDistributionsOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_ListDistributions_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.ListDistributionsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListDistributionsOutput, error)) *CloudFrontClientPort_ListDistributions_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvalidations provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) ListInvalidations(ctx context.Context, input *cloudfront.ListInvalidationsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListInvalidationsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListInvalidations")
	}

	var r0 *cloudfront.ListInvalidationsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListInvalidationsInput, ...func(*cloudfront.Options)) (*cloudfront.ListInvalidationsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListInvalidationsInput, ...func(*cloudfront.Options)) *cloudfront.ListInvalidationsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.ListInvalidationsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.ListInvalidationsInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_ListInvalidations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvalidations'
type CloudFrontClientPort_ListInvalidations_Call struct {
	*mock.Call
}

// ListInvalidations is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.ListInvalidationsInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) ListInvalidations(ctx any, input any, opts ...any) *CloudFrontClientPort_ListInvalidations_Call {
	return &CloudFrontClientPort_ListInvalidations_Call{Call: _e.mock.On("ListInvalidations",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_ListInvalidations_Call) Run(run func(ctx context.Context, input *cloudfront.ListInvalidationsInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_ListInvalidations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.ListInvalidationsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.ListInvalidationsInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_ListInvalidations_Call) Return(listInvalidationsOutput *cloudfront.ListInvalidationsOutput, err error) *CloudFrontClientPort_ListInvalidations_Call {
	_c.Call.Return(listInvalidationsOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_ListInvalidations_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.ListInvalidationsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListInvalidationsOutput, error)) *CloudFrontClientPort_ListInvalidations_Call {
	_c.Call.Return(run)
	return _c
}

// ListOriginAccessControls provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) ListOriginAccessControls(ctx context.Context, input *cloudfront.ListOriginAccessControlsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListOriginAccessControlsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListOriginAccessControls")
	}

	var r0 *cloudfront.ListOriginAccessControlsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListOriginAccessControlsInput, ...func(*cloudfront.Options)) (*cloudfront.ListOriginAccessControlsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.ListOriginAccessControlsInput, ...func(*cloudfront.Options)) *cloudfront.ListOriginAccessControlsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.ListOriginAccessControlsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.ListOriginAccessControlsInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_ListOriginAccessControls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOriginAccessControls'
type CloudFrontClientPort_ListOriginAccessControls_Call struct {
	*mock.Call
}

// ListOriginAccessControls is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.ListOriginAccessControlsInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) ListOriginAccessControls(ctx any, input any, opts ...any) *CloudFrontClientPort_ListOriginAccessControls_Call {
	return &CloudFrontClientPort_ListOriginAccessControls_Call{Call: _e.mock.On("ListOriginAccessControls",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_ListOriginAccessControls_Call) Run(run func(ctx context.Context, input *cloudfront.ListOriginAccessControlsInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_ListOriginAccessControls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.ListOriginAccessControlsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.ListOriginAccessControlsInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_ListOriginAccessControls_Call) Return(listOriginAccessControlsOutput *cloudfront.ListOriginAccessControlsOutput, err error) *CloudFrontClientPort_ListOriginAccessControls_Call {
	_c.Call.Return(listOriginAccessControlsOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_ListOriginAccessControls_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.ListOriginAccessControlsInput, opts ...func(*cloudfront.Options)) (*cloudfront.ListOriginAccessControlsOutput, error)) *CloudFrontClientPort_ListOriginAccessControls_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDistribution provides a mock function for the type CloudFrontClientPort
func (_mock *CloudFrontClientPort) UpdateDistribution(ctx context.Context, input *cloudfront.UpdateDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.UpdateDistributionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateDistribution")
	}

	var r0 *cloudfront.UpdateDistributionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.UpdateDistributionInput, ...func(*cloudfront.Options)) (*cloudfront.UpdateDistributionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudfront.UpdateDistributionInput, ...func(*cloudfront.Options)) *cloudfront.UpdateDistributionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudfront.UpdateDistributionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudfront.UpdateDistributionInput, ...func(*cloudfront.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFrontClientPort_UpdateDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDistribution'
type CloudFrontClientPort_UpdateDistribution_Call struct {
	*mock.Call
}

// UpdateDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudfront.UpdateDistributionInput
//   - opts ...func(*cloudfront.Options)
func (_e *CloudFrontClientPort_Expecter) UpdateDistribution(ctx any, input any, opts ...any) *CloudFrontClientPort_UpdateDistribution_Call {
	return &CloudFrontClientPort_UpdateDistribution_Call{Call: _e.mock.On("UpdateDistribution",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *CloudFrontClientPort_UpdateDistribution_Call) Run(run func(ctx context.Context, input *cloudfront.UpdateDistributionInput, opts ...func(*cloudfront.Options))) *CloudFrontClientPort_UpdateDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudfront.UpdateDistributionInput
		if args[1] != nil {
			arg1 = args[1].(*cloudfront.UpdateDistributionInput)
		}
		var arg2 []func(*cloudfront.Options)
		var variadicArgs []func(*cloudfront.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudfront.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFrontClientPort_UpdateDistribution_Call) Return(updateDistributionOutput *cloudfront.UpdateDistributionOutput, err error) *CloudFrontClientPort_UpdateDistribution_Call {
	_c.Call.Return(updateDistributionOutput, err)
	return _c
}

func (_c *CloudFrontClientPort_UpdateDistribution_Call) RunAndReturn(run func(ctx context.Context, input *cloudfront.UpdateDistributionInput, opts ...func(*cloudfront.Options)) (*cloudfront.UpdateDistributionOutput, error)) *CloudFrontClientPort_UpdateDistribution_Call {
	_c.Call.Return(run)
	return _c
}
