// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	mock "github.com/stretchr/testify/mock"
)

// NewCloudWatchLogsPort creates a new instance of CloudWatchLogsPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudWatchLogsPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudWatchLogsPort {
	mock := &CloudWatchLogsPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CloudWatchLogsPort is an autogenerated mock type for the CloudWatchLogsPort type
type CloudWatchLogsPort struct {
	mock.Mock
}

type CloudWatchLogsPort_Expecter struct {
	mock *mock.Mock
}

func (_m *CloudWatchLogsPort) EXPECT() *CloudWatchLogsPort_Expecter {
	return &CloudWatchLogsPort_Expecter{mock: &_m.Mock}
}

// CreateLogGroup provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) CreateLogGroup(ctx context.Context, input *cloudwatchlogs.CreateLogGroupInput) (*cloudwatchlogs.CreateLogGroupOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogGroup")
	}

	var r0 *cloudwatchlogs.CreateLogGroupOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.CreateLogGroupInput) (*cloudwatchlogs.CreateLogGroupOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.CreateLogGroupInput) *cloudwatchlogs.CreateLogGroupOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.CreateLogGroupOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.CreateLogGroupInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_CreateLogGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogGroup'
type CloudWatchLogsPort_CreateLogGroup_Call struct {
	*mock.Call
}

// CreateLogGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.CreateLogGroupInput
func (_e *CloudWatchLogsPort_Expecter) CreateLogGroup(ctx any, input any) *CloudWatchLogsPort_CreateLogGroup_Call {
	return &CloudWatchLogsPort_CreateLogGroup_Call{Call: _e.mock.On("CreateLogGroup", ctx, input)}
}

func (_c *CloudWatchLogsPort_CreateLogGroup_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.CreateLogGroupInput)) *CloudWatchLogsPort_CreateLogGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.CreateLogGroupInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.CreateLogGroupInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_CreateLogGroup_Call) Return(createLogGroupOutput *cloudwatchlogs.CreateLogGroupOutput, err error) *CloudWatchLogsPort_CreateLogGroup_Call {
	_c.Call.Return(createLogGroupOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_CreateLogGroup_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.CreateLogGroupInput) (*cloudwatchlogs.CreateLogGroupOutput, error)) *CloudWatchLogsPort_CreateLogGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLogStream provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) CreateLogStream(ctx context.Context, input *cloudwatchlogs.CreateLogStreamInput) (*cloudwatchlogs.CreateLogStreamOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogStream")
	}

	var r0 *cloudwatchlogs.CreateLogStreamOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.CreateLogStreamInput) (*cloudwatchlogs.CreateLogStreamOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.CreateLogStreamInput) *cloudwatchlogs.CreateLogStreamOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.CreateLogStreamOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.CreateLogStreamInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_CreateLogStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLogStream'
type CloudWatchLogsPort_CreateLogStream_Call struct {
	*mock.Call
}

// CreateLogStream is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.CreateLogStreamInput
func (_e *CloudWatchLogsPort_Expecter) CreateLogStream(ctx any, input any) *CloudWatchLogsPort_CreateLogStream_Call {
	return &CloudWatchLogsPort_CreateLogStream_Call{Call: _e.mock.On("CreateLogStream", ctx, input)}
}

func (_c *CloudWatchLogsPort_CreateLogStream_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.CreateLogStreamInput)) *CloudWatchLogsPort_CreateLogStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.CreateLogStreamInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.CreateLogStreamInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_CreateLogStream_Call) Return(createLogStreamOutput *cloudwatchlogs.CreateLogStreamOutput, err error) *CloudWatchLogsPort_CreateLogStream_Call {
	_c.Call.Return(createLogStreamOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_CreateLogStream_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.CreateLogStreamInput) (*cloudwatchlogs.CreateLogStreamOutput, error)) *CloudWatchLogsPort_CreateLogStream_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLogGroup provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) DeleteLogGroup(ctx context.Context, input *cloudwatchlogs.DeleteLogGroupInput) (*cloudwatchlogs.DeleteLogGroupOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogGroup")
	}

	var r0 *cloudwatchlogs.DeleteLogGroupOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DeleteLogGroupInput) (*cloudwatchlogs.DeleteLogGroupOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DeleteLogGroupInput) *cloudwatchlogs.DeleteLogGroupOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DeleteLogGroupOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.DeleteLogGroupInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_DeleteLogGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogGroup'
type CloudWatchLogsPort_DeleteLogGroup_Call struct {
	*mock.Call
}

// DeleteLogGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.DeleteLogGroupInput
func (_e *CloudWatchLogsPort_Expecter) DeleteLogGroup(ctx any, input any) *CloudWatchLogsPort_DeleteLogGroup_Call {
	return &CloudWatchLogsPort_DeleteLogGroup_Call{Call: _e.mock.On("DeleteLogGroup", ctx, input)}
}

func (_c *CloudWatchLogsPort_DeleteLogGroup_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.DeleteLogGroupInput)) *CloudWatchLogsPort_DeleteLogGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.DeleteLogGroupInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.DeleteLogGroupInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_DeleteLogGroup_Call) Return(deleteLogGroupOutput *cloudwatchlogs.DeleteLogGroupOutput, err error) *CloudWatchLogsPort_DeleteLogGroup_Call {
	_c.Call.Return(deleteLogGroupOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_DeleteLogGroup_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.DeleteLogGroupInput) (*cloudwatchlogs.DeleteLogGroupOutput, error)) *CloudWatchLogsPort_DeleteLogGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeLogGroups provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) DescribeLogGroups(ctx context.Context, input *cloudwatchlogs.DescribeLogGroupsInput) (*cloudwatchlogs.DescribeLogGroupsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeLogGroups")
	}

	var r0 *cloudwatchlogs.DescribeLogGroupsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput) (*cloudwatchlogs.DescribeLogGroupsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput) *cloudwatchlogs.DescribeLogGroupsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DescribeLogGroupsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_DescribeLogGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeLogGroups'
type CloudWatchLogsPort_DescribeLogGroups_Call struct {
	*mock.Call
}

// DescribeLogGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.DescribeLogGroupsInput
func (_e *CloudWatchLogsPort_Expecter) DescribeLogGroups(ctx any, input any) *CloudWatchLogsPort_DescribeLogGroups_Call {
	return &CloudWatchLogsPort_DescribeLogGroups_Call{Call: _e.mock.On("DescribeLogGroups", ctx, input)}
}

func (_c *CloudWatchLogsPort_DescribeLogGroups_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.DescribeLogGroupsInput)) *CloudWatchLogsPort_DescribeLogGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.DescribeLogGroupsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.DescribeLogGroupsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_DescribeLogGroups_Call) Return(describeLogGroupsOutput *cloudwatchlogs.DescribeLogGroupsOutput, err error) *CloudWatchLogsPort_DescribeLogGroups_Call {
	_c.Call.Return(describeLogGroupsOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_DescribeLogGroups_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.DescribeLogGroupsInput) (*cloudwatchlogs.DescribeLogGroupsOutput, error)) *CloudWatchLogsPort_DescribeLogGroups_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeLogStreams provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) DescribeLogStreams(ctx context.Context, input *cloudwatchlogs.DescribeLogStreamsInput) (*cloudwatchlogs.DescribeLogStreamsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeLogStreams")
	}

	var r0 *cloudwatchlogs.DescribeLogStreamsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeLogStreamsInput) (*cloudwatchlogs.DescribeLogStreamsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeLogStreamsInput) *cloudwatchlogs.DescribeLogStreamsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DescribeLogStreamsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.DescribeLogStreamsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_DescribeLogStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeLogStreams'
type CloudWatchLogsPort_DescribeLogStreams_Call struct {
	*mock.Call
}

// DescribeLogStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.DescribeLogStreamsInput
func (_e *CloudWatchLogsPort_Expecter) DescribeLogStreams(ctx any, input any) *CloudWatchLogsPort_DescribeLogStreams_Call {
	return &CloudWatchLogsPort_DescribeLogStreams_Call{Call: _e.mock.On("DescribeLogStreams", ctx, input)}
}

func (_c *CloudWatchLogsPort_DescribeLogStreams_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.DescribeLogStreamsInput)) *CloudWatchLogsPort_DescribeLogStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.DescribeLogStreamsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.DescribeLogStreamsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_DescribeLogStreams_Call) Return(describeLogStreamsOutput *cloudwatchlogs.DescribeLogStreamsOutput, err error) *CloudWatchLogsPort_DescribeLogStreams_Call {
	_c.Call.Return(describeLogStreamsOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_DescribeLogStreams_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.DescribeLogStreamsInput) (*cloudwatchlogs.DescribeLogStreamsOutput, error)) *CloudWatchLogsPort_DescribeLogStreams_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeMetricFilters provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) DescribeMetricFilters(ctx context.Context, input *cloudwatchlogs.DescribeMetricFiltersInput) (*cloudwatchlogs.DescribeMetricFiltersOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeMetricFilters")
	}

	var r0 *cloudwatchlogs.DescribeMetricFiltersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeMetricFiltersInput) (*cloudwatchlogs.DescribeMetricFiltersOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.DescribeMetricFiltersInput) *cloudwatchlogs.DescribeMetricFiltersOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DescribeMetricFiltersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.DescribeMetricFiltersInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_DescribeMetricFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeMetricFilters'
type CloudWatchLogsPort_DescribeMetricFilters_Call struct {
	*mock.Call
}

// DescribeMetricFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.DescribeMetricFiltersInput
func (_e *CloudWatchLogsPort_Expecter) DescribeMetricFilters(ctx any, input any) *CloudWatchLogsPort_DescribeMetricFilters_Call {
	return &CloudWatchLogsPort_DescribeMetricFilters_Call{Call: _e.mock.On("DescribeMetricFilters", ctx, input)}
}

func (_c *CloudWatchLogsPort_DescribeMetricFilters_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.DescribeMetricFiltersInput)) *CloudWatchLogsPort_DescribeMetricFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.DescribeMetricFiltersInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.DescribeMetricFiltersInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_DescribeMetricFilters_Call) Return(describeMetricFiltersOutput *cloudwatchlogs.DescribeMetricFiltersOutput, err error) *CloudWatchLogsPort_DescribeMetricFilters_Call {
	_c.Call.Return(describeMetricFiltersOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_DescribeMetricFilters_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.DescribeMetricFiltersInput) (*cloudwatchlogs.DescribeMetricFiltersOutput, error)) *CloudWatchLogsPort_DescribeMetricFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogEvents provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) GetLogEvents(ctx context.Context, input *cloudwatchlogs.GetLogEventsInput) (*cloudwatchlogs.GetLogEventsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetLogEvents")
	}

	var r0 *cloudwatchlogs.GetLogEventsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.GetLogEventsInput) (*cloudwatchlogs.GetLogEventsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.GetLogEventsInput) *cloudwatchlogs.GetLogEventsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.GetLogEventsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.GetLogEventsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_GetLogEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogEvents'
type CloudWatchLogsPort_GetLogEvents_Call struct {
	*mock.Call
}

// GetLogEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.GetLogEventsInput
func (_e *CloudWatchLogsPort_Expecter) GetLogEvents(ctx any, input any) *CloudWatchLogsPort_GetLogEvents_Call {
	return &CloudWatchLogsPort_GetLogEvents_Call{Call: _e.mock.On("GetLogEvents", ctx, input)}
}

func (_c *CloudWatchLogsPort_GetLogEvents_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.GetLogEventsInput)) *CloudWatchLogsPort_GetLogEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.GetLogEventsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.GetLogEventsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_GetLogEvents_Call) Return(getLogEventsOutput *cloudwatchlogs.GetLogEventsOutput, err error) *CloudWatchLogsPort_GetLogEvents_Call {
	_c.Call.Return(getLogEventsOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_GetLogEvents_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.GetLogEventsInput) (*cloudwatchlogs.GetLogEventsOutput, error)) *CloudWatchLogsPort_GetLogEvents_Call {
	_c.Call.Return(run)
	return _c
}

// PutLogEvents provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) PutLogEvents(ctx context.Context, input *cloudwatchlogs.PutLogEventsInput) (*cloudwatchlogs.PutLogEventsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutLogEvents")
	}

	var r0 *cloudwatchlogs.PutLogEventsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutLogEventsInput) (*cloudwatchlogs.PutLogEventsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutLogEventsInput) *cloudwatchlogs.PutLogEventsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.PutLogEventsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.PutLogEventsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_PutLogEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutLogEvents'
type CloudWatchLogsPort_PutLogEvents_Call struct {
	*mock.Call
}

// PutLogEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.PutLogEventsInput
func (_e *CloudWatchLogsPort_Expecter) PutLogEvents(ctx any, input any) *CloudWatchLogsPort_PutLogEvents_Call {
	return &CloudWatchLogsPort_PutLogEvents_Call{Call: _e.mock.On("PutLogEvents", ctx, input)}
}

func (_c *CloudWatchLogsPort_PutLogEvents_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.PutLogEventsInput)) *CloudWatchLogsPort_PutLogEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.PutLogEventsInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.PutLogEventsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_PutLogEvents_Call) Return(putLogEventsOutput *cloudwatchlogs.PutLogEventsOutput, err error) *CloudWatchLogsPort_PutLogEvents_Call {
	_c.Call.Return(putLogEventsOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_PutLogEvents_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.PutLogEventsInput) (*cloudwatchlogs.PutLogEventsOutput, error)) *CloudWatchLogsPort_PutLogEvents_Call {
	_c.Call.Return(run)
	return _c
}

// PutMetricFilter provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) PutMetricFilter(ctx context.Context, input *cloudwatchlogs.PutMetricFilterInput) (*cloudwatchlogs.PutMetricFilterOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutMetricFilter")
	}

	var r0 *cloudwatchlogs.PutMetricFilterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutMetricFilterInput) (*cloudwatchlogs.PutMetricFilterOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutMetricFilterInput) *cloudwatchlogs.PutMetricFilterOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.PutMetricFilterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.PutMetricFilterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_PutMetricFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMetricFilter'
type CloudWatchLogsPort_PutMetricFilter_Call struct {
	*mock.Call
}

// PutMetricFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.PutMetricFilterInput
func (_e *CloudWatchLogsPort_Expecter) PutMetricFilter(ctx any, input any) *CloudWatchLogsPort_PutMetricFilter_Call {
	return &CloudWatchLogsPort_PutMetricFilter_Call{Call: _e.mock.On("PutMetricFilter", ctx, input)}
}

func (_c *CloudWatchLogsPort_PutMetricFilter_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.PutMetricFilterInput)) *CloudWatchLogsPort_PutMetricFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.PutMetricFilterInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.PutMetricFilterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_PutMetricFilter_Call) Return(putMetricFilterOutput *cloudwatchlogs.PutMetricFilterOutput, err error) *CloudWatchLogsPort_PutMetricFilter_Call {
	_c.Call.Return(putMetricFilterOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_PutMetricFilter_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.PutMetricFilterInput) (*cloudwatchlogs.PutMetricFilterOutput, error)) *CloudWatchLogsPort_PutMetricFilter_Call {
	_c.Call.Return(run)
	return _c
}

// PutRetentionPolicy provides a mock function for the type CloudWatchLogsPort
func (_mock *CloudWatchLogsPort) PutRetentionPolicy(ctx context.Context, input *cloudwatchlogs.PutRetentionPolicyInput) (*cloudwatchlogs.PutRetentionPolicyOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutRetentionPolicy")
	}

	var r0 *cloudwatchlogs.PutRetentionPolicyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutRetentionPolicyInput) (*cloudwatchlogs.PutRetentionPolicyOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudwatchlogs.PutRetentionPolicyInput) *cloudwatchlogs.PutRetentionPolicyOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.PutRetentionPolicyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudwatchlogs.PutRetentionPolicyInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudWatchLogsPort_PutRetentionPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRetentionPolicy'
type CloudWatchLogsPort_PutRetentionPolicy_Call struct {
	*mock.Call
}

// PutRetentionPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudwatchlogs.PutRetentionPolicyInput
func (_e *CloudWatchLogsPort_Expecter) PutRetentionPolicy(ctx any, input any) *CloudWatchLogsPort_PutRetentionPolicy_Call {
	return &CloudWatchLogsPort_PutRetentionPolicy_Call{Call: _e.mock.On("PutRetentionPolicy", ctx, input)}
}

func (_c *CloudWatchLogsPort_PutRetentionPolicy_Call) Run(run func(ctx context.Context, input *cloudwatchlogs.PutRetentionPolicyInput)) *CloudWatchLogsPort_PutRetentionPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudwatchlogs.PutRetentionPolicyInput
		if args[1] != nil {
			arg1 = args[1].(*cloudwatchlogs.PutRetentionPolicyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CloudWatchLogsPort_PutRetentionPolicy_Call) Return(putRetentionPolicyOutput *cloudwatchlogs.PutRetentionPolicyOutput, err error) *CloudWatchLogsPort_PutRetentionPolicy_Call {
	_c.Call.Return(putRetentionPolicyOutput, err)
	return _c
}

func (_c *CloudWatchLogsPort_PutRetentionPolicy_Call) RunAndReturn(run func(ctx context.Context, input *cloudwatchlogs.PutRetentionPolicyInput) (*cloudwatchlogs.PutRetentionPolicyOutput, error)) *CloudWatchLogsPort_PutRetentionPolicy_Call {
	_c.Call.Return(run)
	return _c
}
