// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	mock "github.com/stretchr/testify/mock"
)

// NewCloudFormationClientPort creates a new instance of CloudFormationClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCloudFormationClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudFormationClientPort {
	mock := &CloudFormationClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CloudFormationClientPort is an autogenerated mock type for the CloudFormationClientPort type
type CloudFormationClientPort struct {
	mock.Mock
}

type CloudFormationClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *CloudFormationClientPort) EXPECT() *CloudFormationClientPort_Expecter {
	return &CloudFormationClientPort_Expecter{mock: &_m.Mock}
}

// CreateStack provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) CreateStack(ctx context.Context, input *cloudformation.CreateStackInput, opts ...func(*cloudformation.Options)) (*cloudformation.CreateStackOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateStack")
	}

	var r0 *cloudformation.CreateStackOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.CreateStackInput, ...func(*cloudformation.Options)) (*cloudformation.CreateStackOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.CreateStackInput, ...func(*cloudformation.Options)) *cloudformation.CreateStackOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.CreateStackOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.CreateStackInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_CreateStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStack'
type CloudFormationClientPort_CreateStack_Call struct {
	*mock.Call
}

// CreateStack is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.CreateStackInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) CreateStack(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_CreateStack_Call {
	return &CloudFormationClientPort_CreateStack_Call{Call: _e.mock.On("CreateStack",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_CreateStack_Call) Run(run func(ctx context.Context, input *cloudformation.CreateStackInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_CreateStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.CreateStackInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.CreateStackInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_CreateStack_Call) Return(createStackOutput *cloudformation.CreateStackOutput, err error) *CloudFormationClientPort_CreateStack_Call {
	_c.Call.Return(createStackOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_CreateStack_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.CreateStackInput, opts ...func(*cloudformation.Options)) (*cloudformation.CreateStackOutput, error)) *CloudFormationClientPort_CreateStack_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStack provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) DeleteStack(ctx context.Context, input *cloudformation.DeleteStackInput, opts ...func(*cloudformation.Options)) (*cloudformation.DeleteStackOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteStack")
	}

	var r0 *cloudformation.DeleteStackOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.DeleteStackInput, ...func(*cloudformation.Options)) (*cloudformation.DeleteStackOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.DeleteStackInput, ...func(*cloudformation.Options)) *cloudformation.DeleteStackOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.DeleteStackOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.DeleteStackInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_DeleteStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStack'
type CloudFormationClientPort_DeleteStack_Call struct {
	*mock.Call
}

// DeleteStack is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.DeleteStackInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) DeleteStack(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_DeleteStack_Call {
	return &CloudFormationClientPort_DeleteStack_Call{Call: _e.mock.On("DeleteStack",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_DeleteStack_Call) Run(run func(ctx context.Context, input *cloudformation.DeleteStackInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_DeleteStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.DeleteStackInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.DeleteStackInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_DeleteStack_Call) Return(deleteStackOutput *cloudformation.DeleteStackOutput, err error) *CloudFormationClientPort_DeleteStack_Call {
	_c.Call.Return(deleteStackOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_DeleteStack_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.DeleteStackInput, opts ...func(*cloudformation.Options)) (*cloudformation.DeleteStackOutput, error)) *CloudFormationClientPort_DeleteStack_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeStacks provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) DescribeStacks(ctx context.Context, input *cloudformation.DescribeStacksInput, opts ...func(*cloudformation.Options)) (*cloudformation.DescribeStacksOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeStacks")
	}

	var r0 *cloudformation.DescribeStacksOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.DescribeStacksInput, ...func(*cloudformation.Options)) (*cloudformation.DescribeStacksOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.DescribeStacksInput, ...func(*cloudformation.Options)) *cloudformation.DescribeStacksOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.DescribeStacksOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.DescribeStacksInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_DescribeStacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeStacks'
type CloudFormationClientPort_DescribeStacks_Call struct {
	*mock.Call
}

// DescribeStacks is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.DescribeStacksInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) DescribeStacks(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_DescribeStacks_Call {
	return &CloudFormationClientPort_DescribeStacks_Call{Call: _e.mock.On("DescribeStacks",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_DescribeStacks_Call) Run(run func(ctx context.Context, input *cloudformation.DescribeStacksInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_DescribeStacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.DescribeStacksInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.DescribeStacksInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_DescribeStacks_Call) Return(describeStacksOutput *cloudformation.DescribeStacksOutput, err error) *CloudFormationClientPort_DescribeStacks_Call {
	_c.Call.Return(describeStacksOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_DescribeStacks_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.DescribeStacksInput, opts ...func(*cloudformation.Options)) (*cloudformation.DescribeStacksOutput, error)) *CloudFormationClientPort_DescribeStacks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) GetTemplate(ctx context.Context, input *cloudformation.GetTemplateInput, opts ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 *cloudformation.GetTemplateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.GetTemplateInput, ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.GetTemplateInput, ...func(*cloudformation.Options)) *cloudformation.GetTemplateOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.GetTemplateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.GetTemplateInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type CloudFormationClientPort_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.GetTemplateInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) GetTemplate(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_GetTemplate_Call {
	return &CloudFormationClientPort_GetTemplate_Call{Call: _e.mock.On("GetTemplate",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_GetTemplate_Call) Run(run func(ctx context.Context, input *cloudformation.GetTemplateInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.GetTemplateInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.GetTemplateInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_GetTemplate_Call) Return(getTemplateOutput *cloudformation.GetTemplateOutput, err error) *CloudFormationClientPort_GetTemplate_Call {
	_c.Call.Return(getTemplateOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_GetTemplate_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.GetTemplateInput, opts ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error)) *CloudFormationClientPort_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListStackResources provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) ListStackResources(ctx context.Context, input *cloudformation.ListStackResourcesInput, opts ...func(*cloudformation.Options)) (*cloudformation.ListStackResourcesOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListStackResources")
	}

	var r0 *cloudformation.ListStackResourcesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.ListStackResourcesInput, ...func(*cloudformation.Options)) (*cloudformation.ListStackResourcesOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.ListStackResourcesInput, ...func(*cloudformation.Options)) *cloudformation.ListStackResourcesOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.ListStackResourcesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.ListStackResourcesInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_ListStackResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStackResources'
type CloudFormationClientPort_ListStackResources_Call struct {
	*mock.Call
}

// ListStackResources is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.ListStackResourcesInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) ListStackResources(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_ListStackResources_Call {
	return &CloudFormationClientPort_ListStackResources_Call{Call: _e.mock.On("ListStackResources",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_ListStackResources_Call) Run(run func(ctx context.Context, input *cloudformation.ListStackResourcesInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_ListStackResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.ListStackResourcesInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.ListStackResourcesInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_ListStackResources_Call) Return(listStackResourcesOutput *cloudformation.ListStackResourcesOutput, err error) *CloudFormationClientPort_ListStackResources_Call {
	_c.Call.Return(listStackResourcesOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_ListStackResources_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.ListStackResourcesInput, opts ...func(*cloudformation.Options)) (*cloudformation.ListStackResourcesOutput, error)) *CloudFormationClientPort_ListStackResources_Call {
	_c.Call.Return(run)
	return _c
}

// ListStacks provides a mock function for the type CloudFormationClientPort
func (_mock *CloudFormationClientPort) ListStacks(ctx context.Context, input *cloudformation.ListStacksInput, opts ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListStacks")
	}

	var r0 *cloudformation.ListStacksOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.ListStacksInput, ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudformation.ListStacksInput, ...func(*cloudformation.Options)) *cloudformation.ListStacksOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudformation.ListStacksOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudformation.ListStacksInput, ...func(*cloudformation.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CloudFormationClientPort_ListStacks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStacks'
type CloudFormationClientPort_ListStacks_Call struct {
	*mock.Call
}

// ListStacks is a helper method to define mock.On call
//   - ctx context.Context
//   - input *cloudformation.ListStacksInput
//   - opts ...func(*cloudformation.Options)
func (_e *CloudFormationClientPort_Expecter) ListStacks(ctx interface{}, input interface{}, opts ...interface{}) *CloudFormationClientPort_ListStacks_Call {
	return &CloudFormationClientPort_ListStacks_Call{Call: _e.mock.On("ListStacks",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *CloudFormationClientPort_ListStacks_Call) Run(run func(ctx context.Context, input *cloudformation.ListStacksInput, opts ...func(*cloudformation.Options))) *CloudFormationClientPort_ListStacks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudformation.ListStacksInput
		if args[1] != nil {
			arg1 = args[1].(*cloudformation.ListStacksInput)
		}
		var arg2 []func(*cloudformation.Options)
		var variadicArgs []func(*cloudformation.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*cloudformation.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CloudFormationClientPort_ListStacks_Call) Return(listStacksOutput *cloudformation.ListStacksOutput, err error) *CloudFormationClientPort_ListStacks_Call {
	_c.Call.Return(listStacksOutput, err)
	return _c
}

func (_c *CloudFormationClientPort_ListStacks_Call) RunAndReturn(run func(ctx context.Context, input *cloudformation.ListStacksInput, opts ...func(*cloudformation.Options)) (*cloudformation.ListStacksOutput, error)) *CloudFormationClientPort_ListStacks_Call {
	_c.Call.Return(run)
	return _c
}
