// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodbstreams"
	mock "github.com/stretchr/testify/mock"
)

// NewDynamoDBStreamsPort creates a new instance of DynamoDBStreamsPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoDBStreamsPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoDBStreamsPort {
	mock := &DynamoDBStreamsPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DynamoDBStreamsPort is an autogenerated mock type for the DynamoDBStreamsPort type
type DynamoDBStreamsPort struct {
	mock.Mock
}

type DynamoDBStreamsPort_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamoDBStreamsPort) EXPECT() *DynamoDBStreamsPort_Expecter {
	return &DynamoDBStreamsPort_Expecter{mock: &_m.Mock}
}

// DescribeStream provides a mock function for the type DynamoDBStreamsPort
func (_mock *DynamoDBStreamsPort) DescribeStream(ctx context.Context, input *dynamodbstreams.DescribeStreamInput) (*dynamodbstreams.DescribeStreamOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeStream")
	}

	var r0 *dynamodbstreams.DescribeStreamOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.DescribeStreamInput) (*dynamodbstreams.DescribeStreamOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.DescribeStreamInput) *dynamodbstreams.DescribeStreamOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodbstreams.DescribeStreamOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodbstreams.DescribeStreamInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBStreamsPort_DescribeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeStream'
type DynamoDBStreamsPort_DescribeStream_Call struct {
	*mock.Call
}

// DescribeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodbstreams.DescribeStreamInput
func (_e *DynamoDBStreamsPort_Expecter) DescribeStream(ctx interface{}, input interface{}) *DynamoDBStreamsPort_DescribeStream_Call {
	return &DynamoDBStreamsPort_DescribeStream_Call{Call: _e.mock.On("DescribeStream", ctx, input)}
}

func (_c *DynamoDBStreamsPort_DescribeStream_Call) Run(run func(ctx context.Context, input *dynamodbstreams.DescribeStreamInput)) *DynamoDBStreamsPort_DescribeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodbstreams.DescribeStreamInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodbstreams.DescribeStreamInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBStreamsPort_DescribeStream_Call) Return(describeStreamOutput *dynamodbstreams.DescribeStreamOutput, err error) *DynamoDBStreamsPort_DescribeStream_Call {
	_c.Call.Return(describeStreamOutput, err)
	return _c
}

func (_c *DynamoDBStreamsPort_DescribeStream_Call) RunAndReturn(run func(ctx context.Context, input *dynamodbstreams.DescribeStreamInput) (*dynamodbstreams.DescribeStreamOutput, error)) *DynamoDBStreamsPort_DescribeStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecords provides a mock function for the type DynamoDBStreamsPort
func (_mock *DynamoDBStreamsPort) GetRecords(ctx context.Context, input *dynamodbstreams.GetRecordsInput) (*dynamodbstreams.GetRecordsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRecords")
	}

	var r0 *dynamodbstreams.GetRecordsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.GetRecordsInput) (*dynamodbstreams.GetRecordsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.GetRecordsInput) *dynamodbstreams.GetRecordsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodbstreams.GetRecordsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodbstreams.GetRecordsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBStreamsPort_GetRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecords'
type DynamoDBStreamsPort_GetRecords_Call struct {
	*mock.Call
}

// GetRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodbstreams.GetRecordsInput
func (_e *DynamoDBStreamsPort_Expecter) GetRecords(ctx interface{}, input interface{}) *DynamoDBStreamsPort_GetRecords_Call {
	return &DynamoDBStreamsPort_GetRecords_Call{Call: _e.mock.On("GetRecords", ctx, input)}
}

func (_c *DynamoDBStreamsPort_GetRecords_Call) Run(run func(ctx context.Context, input *dynamodbstreams.GetRecordsInput)) *DynamoDBStreamsPort_GetRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodbstreams.GetRecordsInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodbstreams.GetRecordsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBStreamsPort_GetRecords_Call) Return(getRecordsOutput *dynamodbstreams.GetRecordsOutput, err error) *DynamoDBStreamsPort_GetRecords_Call {
	_c.Call.Return(getRecordsOutput, err)
	return _c
}

func (_c *DynamoDBStreamsPort_GetRecords_Call) RunAndReturn(run func(ctx context.Context, input *dynamodbstreams.GetRecordsInput) (*dynamodbstreams.GetRecordsOutput, error)) *DynamoDBStreamsPort_GetRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetShardIterator provides a mock function for the type DynamoDBStreamsPort
func (_mock *DynamoDBStreamsPort) GetShardIterator(ctx context.Context, input *dynamodbstreams.GetShardIteratorInput) (*dynamodbstreams.GetShardIteratorOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetShardIterator")
	}

	var r0 *dynamodbstreams.GetShardIteratorOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.GetShardIteratorInput) (*dynamodbstreams.GetShardIteratorOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.GetShardIteratorInput) *dynamodbstreams.GetShardIteratorOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodbstreams.GetShardIteratorOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodbstreams.GetShardIteratorInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBStreamsPort_GetShardIterator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShardIterator'
type DynamoDBStreamsPort_GetShardIterator_Call struct {
	*mock.Call
}

// GetShardIterator is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodbstreams.GetShardIteratorInput
func (_e *DynamoDBStreamsPort_Expecter) GetShardIterator(ctx interface{}, input interface{}) *DynamoDBStreamsPort_GetShardIterator_Call {
	return &DynamoDBStreamsPort_GetShardIterator_Call{Call: _e.mock.On("GetShardIterator", ctx, input)}
}

func (_c *DynamoDBStreamsPort_GetShardIterator_Call) Run(run func(ctx context.Context, input *dynamodbstreams.GetShardIteratorInput)) *DynamoDBStreamsPort_GetShardIterator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodbstreams.GetShardIteratorInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodbstreams.GetShardIteratorInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBStreamsPort_GetShardIterator_Call) Return(getShardIteratorOutput *dynamodbstreams.GetShardIteratorOutput, err error) *DynamoDBStreamsPort_GetShardIterator_Call {
	_c.Call.Return(getShardIteratorOutput, err)
	return _c
}

func (_c *DynamoDBStreamsPort_GetShardIterator_Call) RunAndReturn(run func(ctx context.Context, input *dynamodbstreams.GetShardIteratorInput) (*dynamodbstreams.GetShardIteratorOutput, error)) *DynamoDBStreamsPort_GetShardIterator_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreams provides a mock function for the type DynamoDBStreamsPort
func (_mock *DynamoDBStreamsPort) ListStreams(ctx context.Context, input *dynamodbstreams.ListStreamsInput) (*dynamodbstreams.ListStreamsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListStreams")
	}

	var r0 *dynamodbstreams.ListStreamsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.ListStreamsInput) (*dynamodbstreams.ListStreamsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodbstreams.ListStreamsInput) *dynamodbstreams.ListStreamsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodbstreams.ListStreamsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodbstreams.ListStreamsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBStreamsPort_ListStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreams'
type DynamoDBStreamsPort_ListStreams_Call struct {
	*mock.Call
}

// ListStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodbstreams.ListStreamsInput
func (_e *DynamoDBStreamsPort_Expecter) ListStreams(ctx interface{}, input interface{}) *DynamoDBStreamsPort_ListStreams_Call {
	return &DynamoDBStreamsPort_ListStreams_Call{Call: _e.mock.On("ListStreams", ctx, input)}
}

func (_c *DynamoDBStreamsPort_ListStreams_Call) Run(run func(ctx context.Context, input *dynamodbstreams.ListStreamsInput)) *DynamoDBStreamsPort_ListStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodbstreams.ListStreamsInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodbstreams.ListStreamsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBStreamsPort_ListStreams_Call) Return(listStreamsOutput *dynamodbstreams.ListStreamsOutput, err error) *DynamoDBStreamsPort_ListStreams_Call {
	_c.Call.Return(listStreamsOutput, err)
	return _c
}

func (_c *DynamoDBStreamsPort_ListStreams_Call) RunAndReturn(run func(ctx context.Context, input *dynamodbstreams.ListStreamsInput) (*dynamodbstreams.ListStreamsOutput, error)) *DynamoDBStreamsPort_ListStreams_Call {
	_c.Call.Return(run)
	return _c
}
