// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ec2"
	mock "github.com/stretchr/testify/mock"
)

// NewEC2Port creates a new instance of EC2Port. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEC2Port(t interface {
	mock.TestingT
	Cleanup(func())
}) *EC2Port {
	mock := &EC2Port{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EC2Port is an autogenerated mock type for the EC2Port type
type EC2Port struct {
	mock.Mock
}

type EC2Port_Expecter struct {
	mock *mock.Mock
}

func (_m *EC2Port) EXPECT() *EC2Port_Expecter {
	return &EC2Port_Expecter{mock: &_m.Mock}
}

// AuthorizeSecurityGroupIngress provides a mock function for the type EC2Port
func (_mock *EC2Port) AuthorizeSecurityGroupIngress(ctx context.Context, input *ec2.AuthorizeSecurityGroupIngressInput) (*ec2.AuthorizeSecurityGroupIngressOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeSecurityGroupIngress")
	}

	var r0 *ec2.AuthorizeSecurityGroupIngressOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.AuthorizeSecurityGroupIngressInput) (*ec2.AuthorizeSecurityGroupIngressOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.AuthorizeSecurityGroupIngressInput) *ec2.AuthorizeSecurityGroupIngressOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.AuthorizeSecurityGroupIngressOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.AuthorizeSecurityGroupIngressInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_AuthorizeSecurityGroupIngress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeSecurityGroupIngress'
type EC2Port_AuthorizeSecurityGroupIngress_Call struct {
	*mock.Call
}

// AuthorizeSecurityGroupIngress is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.AuthorizeSecurityGroupIngressInput
func (_e *EC2Port_Expecter) AuthorizeSecurityGroupIngress(ctx any, input any) *EC2Port_AuthorizeSecurityGroupIngress_Call {
	return &EC2Port_AuthorizeSecurityGroupIngress_Call{Call: _e.mock.On("AuthorizeSecurityGroupIngress", ctx, input)}
}

func (_c *EC2Port_AuthorizeSecurityGroupIngress_Call) Run(run func(ctx context.Context, input *ec2.AuthorizeSecurityGroupIngressInput)) *EC2Port_AuthorizeSecurityGroupIngress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.AuthorizeSecurityGroupIngressInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.AuthorizeSecurityGroupIngressInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_AuthorizeSecurityGroupIngress_Call) Return(authorizeSecurityGroupIngressOutput *ec2.AuthorizeSecurityGroupIngressOutput, err error) *EC2Port_AuthorizeSecurityGroupIngress_Call {
	_c.Call.Return(authorizeSecurityGroupIngressOutput, err)
	return _c
}

func (_c *EC2Port_AuthorizeSecurityGroupIngress_Call) RunAndReturn(run func(ctx context.Context, input *ec2.AuthorizeSecurityGroupIngressInput) (*ec2.AuthorizeSecurityGroupIngressOutput, error)) *EC2Port_AuthorizeSecurityGroupIngress_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeyPair provides a mock function for the type EC2Port
func (_mock *EC2Port) CreateKeyPair(ctx context.Context, input *ec2.CreateKeyPairInput) (*ec2.CreateKeyPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateKeyPair")
	}

	var r0 *ec2.CreateKeyPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateKeyPairInput) (*ec2.CreateKeyPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateKeyPairInput) *ec2.CreateKeyPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.CreateKeyPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.CreateKeyPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_CreateKeyPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeyPair'
type EC2Port_CreateKeyPair_Call struct {
	*mock.Call
}

// CreateKeyPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.CreateKeyPairInput
func (_e *EC2Port_Expecter) CreateKeyPair(ctx any, input any) *EC2Port_CreateKeyPair_Call {
	return &EC2Port_CreateKeyPair_Call{Call: _e.mock.On("CreateKeyPair", ctx, input)}
}

func (_c *EC2Port_CreateKeyPair_Call) Run(run func(ctx context.Context, input *ec2.CreateKeyPairInput)) *EC2Port_CreateKeyPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.CreateKeyPairInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.CreateKeyPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_CreateKeyPair_Call) Return(createKeyPairOutput *ec2.CreateKeyPairOutput, err error) *EC2Port_CreateKeyPair_Call {
	_c.Call.Return(createKeyPairOutput, err)
	return _c
}

func (_c *EC2Port_CreateKeyPair_Call) RunAndReturn(run func(ctx context.Context, input *ec2.CreateKeyPairInput) (*ec2.CreateKeyPairOutput, error)) *EC2Port_CreateKeyPair_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecurityGroup provides a mock function for the type EC2Port
func (_mock *EC2Port) CreateSecurityGroup(ctx context.Context, input *ec2.CreateSecurityGroupInput) (*ec2.CreateSecurityGroupOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecurityGroup")
	}

	var r0 *ec2.CreateSecurityGroupOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateSecurityGroupInput) (*ec2.CreateSecurityGroupOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.CreateSecurityGroupInput) *ec2.CreateSecurityGroupOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.CreateSecurityGroupOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.CreateSecurityGroupInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_CreateSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecurityGroup'
type EC2Port_CreateSecurityGroup_Call struct {
	*mock.Call
}

// CreateSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.CreateSecurityGroupInput
func (_e *EC2Port_Expecter) CreateSecurityGroup(ctx any, input any) *EC2Port_CreateSecurityGroup_Call {
	return &EC2Port_CreateSecurityGroup_Call{Call: _e.mock.On("CreateSecurityGroup", ctx, input)}
}

func (_c *EC2Port_CreateSecurityGroup_Call) Run(run func(ctx context.Context, input *ec2.CreateSecurityGroupInput)) *EC2Port_CreateSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.CreateSecurityGroupInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.CreateSecurityGroupInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_CreateSecurityGroup_Call) Return(createSecurityGroupOutput *ec2.CreateSecurityGroupOutput, err error) *EC2Port_CreateSecurityGroup_Call {
	_c.Call.Return(createSecurityGroupOutput, err)
	return _c
}

func (_c *EC2Port_CreateSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, input *ec2.CreateSecurityGroupInput) (*ec2.CreateSecurityGroupOutput, error)) *EC2Port_CreateSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyPair provides a mock function for the type EC2Port
func (_mock *EC2Port) DeleteKeyPair(ctx context.Context, input *ec2.DeleteKeyPairInput) (*ec2.DeleteKeyPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyPair")
	}

	var r0 *ec2.DeleteKeyPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DeleteKeyPairInput) (*ec2.DeleteKeyPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DeleteKeyPairInput) *ec2.DeleteKeyPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DeleteKeyPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DeleteKeyPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DeleteKeyPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyPair'
type EC2Port_DeleteKeyPair_Call struct {
	*mock.Call
}

// DeleteKeyPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DeleteKeyPairInput
func (_e *EC2Port_Expecter) DeleteKeyPair(ctx any, input any) *EC2Port_DeleteKeyPair_Call {
	return &EC2Port_DeleteKeyPair_Call{Call: _e.mock.On("DeleteKeyPair", ctx, input)}
}

func (_c *EC2Port_DeleteKeyPair_Call) Run(run func(ctx context.Context, input *ec2.DeleteKeyPairInput)) *EC2Port_DeleteKeyPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DeleteKeyPairInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DeleteKeyPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DeleteKeyPair_Call) Return(deleteKeyPairOutput *ec2.DeleteKeyPairOutput, err error) *EC2Port_DeleteKeyPair_Call {
	_c.Call.Return(deleteKeyPairOutput, err)
	return _c
}

func (_c *EC2Port_DeleteKeyPair_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DeleteKeyPairInput) (*ec2.DeleteKeyPairOutput, error)) *EC2Port_DeleteKeyPair_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecurityGroup provides a mock function for the type EC2Port
func (_mock *EC2Port) DeleteSecurityGroup(ctx context.Context, input *ec2.DeleteSecurityGroupInput) (*ec2.DeleteSecurityGroupOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecurityGroup")
	}

	var r0 *ec2.DeleteSecurityGroupOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DeleteSecurityGroupInput) (*ec2.DeleteSecurityGroupOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DeleteSecurityGroupInput) *ec2.DeleteSecurityGroupOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DeleteSecurityGroupOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DeleteSecurityGroupInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DeleteSecurityGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecurityGroup'
type EC2Port_DeleteSecurityGroup_Call struct {
	*mock.Call
}

// DeleteSecurityGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DeleteSecurityGroupInput
func (_e *EC2Port_Expecter) DeleteSecurityGroup(ctx any, input any) *EC2Port_DeleteSecurityGroup_Call {
	return &EC2Port_DeleteSecurityGroup_Call{Call: _e.mock.On("DeleteSecurityGroup", ctx, input)}
}

func (_c *EC2Port_DeleteSecurityGroup_Call) Run(run func(ctx context.Context, input *ec2.DeleteSecurityGroupInput)) *EC2Port_DeleteSecurityGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DeleteSecurityGroupInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DeleteSecurityGroupInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DeleteSecurityGroup_Call) Return(deleteSecurityGroupOutput *ec2.DeleteSecurityGroupOutput, err error) *EC2Port_DeleteSecurityGroup_Call {
	_c.Call.Return(deleteSecurityGroupOutput, err)
	return _c
}

func (_c *EC2Port_DeleteSecurityGroup_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DeleteSecurityGroupInput) (*ec2.DeleteSecurityGroupOutput, error)) *EC2Port_DeleteSecurityGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeInstances provides a mock function for the type EC2Port
func (_mock *EC2Port) DescribeInstances(ctx context.Context, input *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeInstances")
	}

	var r0 *ec2.DescribeInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeInstancesInput) *ec2.DescribeInstancesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeInstancesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DescribeInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeInstances'
type EC2Port_DescribeInstances_Call struct {
	*mock.Call
}

// DescribeInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DescribeInstancesInput
func (_e *EC2Port_Expecter) DescribeInstances(ctx any, input any) *EC2Port_DescribeInstances_Call {
	return &EC2Port_DescribeInstances_Call{Call: _e.mock.On("DescribeInstances", ctx, input)}
}

func (_c *EC2Port_DescribeInstances_Call) Run(run func(ctx context.Context, input *ec2.DescribeInstancesInput)) *EC2Port_DescribeInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeInstancesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DescribeInstances_Call) Return(describeInstancesOutput *ec2.DescribeInstancesOutput, err error) *EC2Port_DescribeInstances_Call {
	_c.Call.Return(describeInstancesOutput, err)
	return _c
}

func (_c *EC2Port_DescribeInstances_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DescribeInstancesInput) (*ec2.DescribeInstancesOutput, error)) *EC2Port_DescribeInstances_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeKeyPairs provides a mock function for the type EC2Port
func (_mock *EC2Port) DescribeKeyPairs(ctx context.Context, input *ec2.DescribeKeyPairsInput) (*ec2.DescribeKeyPairsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeKeyPairs")
	}

	var r0 *ec2.DescribeKeyPairsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeKeyPairsInput) (*ec2.DescribeKeyPairsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeKeyPairsInput) *ec2.DescribeKeyPairsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeKeyPairsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeKeyPairsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DescribeKeyPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeKeyPairs'
type EC2Port_DescribeKeyPairs_Call struct {
	*mock.Call
}

// DescribeKeyPairs is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DescribeKeyPairsInput
func (_e *EC2Port_Expecter) DescribeKeyPairs(ctx any, input any) *EC2Port_DescribeKeyPairs_Call {
	return &EC2Port_DescribeKeyPairs_Call{Call: _e.mock.On("DescribeKeyPairs", ctx, input)}
}

func (_c *EC2Port_DescribeKeyPairs_Call) Run(run func(ctx context.Context, input *ec2.DescribeKeyPairsInput)) *EC2Port_DescribeKeyPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeKeyPairsInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeKeyPairsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DescribeKeyPairs_Call) Return(describeKeyPairsOutput *ec2.DescribeKeyPairsOutput, err error) *EC2Port_DescribeKeyPairs_Call {
	_c.Call.Return(describeKeyPairsOutput, err)
	return _c
}

func (_c *EC2Port_DescribeKeyPairs_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DescribeKeyPairsInput) (*ec2.DescribeKeyPairsOutput, error)) *EC2Port_DescribeKeyPairs_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSecurityGroups provides a mock function for the type EC2Port
func (_mock *EC2Port) DescribeSecurityGroups(ctx context.Context, input *ec2.DescribeSecurityGroupsInput) (*ec2.DescribeSecurityGroupsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSecurityGroups")
	}

	var r0 *ec2.DescribeSecurityGroupsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeSecurityGroupsInput) (*ec2.DescribeSecurityGroupsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeSecurityGroupsInput) *ec2.DescribeSecurityGroupsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeSecurityGroupsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeSecurityGroupsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DescribeSecurityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSecurityGroups'
type EC2Port_DescribeSecurityGroups_Call struct {
	*mock.Call
}

// DescribeSecurityGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DescribeSecurityGroupsInput
func (_e *EC2Port_Expecter) DescribeSecurityGroups(ctx any, input any) *EC2Port_DescribeSecurityGroups_Call {
	return &EC2Port_DescribeSecurityGroups_Call{Call: _e.mock.On("DescribeSecurityGroups", ctx, input)}
}

func (_c *EC2Port_DescribeSecurityGroups_Call) Run(run func(ctx context.Context, input *ec2.DescribeSecurityGroupsInput)) *EC2Port_DescribeSecurityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeSecurityGroupsInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeSecurityGroupsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DescribeSecurityGroups_Call) Return(describeSecurityGroupsOutput *ec2.DescribeSecurityGroupsOutput, err error) *EC2Port_DescribeSecurityGroups_Call {
	_c.Call.Return(describeSecurityGroupsOutput, err)
	return _c
}

func (_c *EC2Port_DescribeSecurityGroups_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DescribeSecurityGroupsInput) (*ec2.DescribeSecurityGroupsOutput, error)) *EC2Port_DescribeSecurityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSubnets provides a mock function for the type EC2Port
func (_mock *EC2Port) DescribeSubnets(ctx context.Context, input *ec2.DescribeSubnetsInput) (*ec2.DescribeSubnetsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSubnets")
	}

	var r0 *ec2.DescribeSubnetsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeSubnetsInput) (*ec2.DescribeSubnetsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeSubnetsInput) *ec2.DescribeSubnetsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeSubnetsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeSubnetsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DescribeSubnets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSubnets'
type EC2Port_DescribeSubnets_Call struct {
	*mock.Call
}

// DescribeSubnets is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DescribeSubnetsInput
func (_e *EC2Port_Expecter) DescribeSubnets(ctx any, input any) *EC2Port_DescribeSubnets_Call {
	return &EC2Port_DescribeSubnets_Call{Call: _e.mock.On("DescribeSubnets", ctx, input)}
}

func (_c *EC2Port_DescribeSubnets_Call) Run(run func(ctx context.Context, input *ec2.DescribeSubnetsInput)) *EC2Port_DescribeSubnets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeSubnetsInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeSubnetsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DescribeSubnets_Call) Return(describeSubnetsOutput *ec2.DescribeSubnetsOutput, err error) *EC2Port_DescribeSubnets_Call {
	_c.Call.Return(describeSubnetsOutput, err)
	return _c
}

func (_c *EC2Port_DescribeSubnets_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DescribeSubnetsInput) (*ec2.DescribeSubnetsOutput, error)) *EC2Port_DescribeSubnets_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeVpcs provides a mock function for the type EC2Port
func (_mock *EC2Port) DescribeVpcs(ctx context.Context, input *ec2.DescribeVpcsInput) (*ec2.DescribeVpcsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeVpcs")
	}

	var r0 *ec2.DescribeVpcsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeVpcsInput) (*ec2.DescribeVpcsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.DescribeVpcsInput) *ec2.DescribeVpcsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.DescribeVpcsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.DescribeVpcsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_DescribeVpcs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeVpcs'
type EC2Port_DescribeVpcs_Call struct {
	*mock.Call
}

// DescribeVpcs is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.DescribeVpcsInput
func (_e *EC2Port_Expecter) DescribeVpcs(ctx any, input any) *EC2Port_DescribeVpcs_Call {
	return &EC2Port_DescribeVpcs_Call{Call: _e.mock.On("DescribeVpcs", ctx, input)}
}

func (_c *EC2Port_DescribeVpcs_Call) Run(run func(ctx context.Context, input *ec2.DescribeVpcsInput)) *EC2Port_DescribeVpcs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.DescribeVpcsInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.DescribeVpcsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_DescribeVpcs_Call) Return(describeVpcsOutput *ec2.DescribeVpcsOutput, err error) *EC2Port_DescribeVpcs_Call {
	_c.Call.Return(describeVpcsOutput, err)
	return _c
}

func (_c *EC2Port_DescribeVpcs_Call) RunAndReturn(run func(ctx context.Context, input *ec2.DescribeVpcsInput) (*ec2.DescribeVpcsOutput, error)) *EC2Port_DescribeVpcs_Call {
	_c.Call.Return(run)
	return _c
}

// ImportKeyPair provides a mock function for the type EC2Port
func (_mock *EC2Port) ImportKeyPair(ctx context.Context, input *ec2.ImportKeyPairInput) (*ec2.ImportKeyPairOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ImportKeyPair")
	}

	var r0 *ec2.ImportKeyPairOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.ImportKeyPairInput) (*ec2.ImportKeyPairOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.ImportKeyPairInput) *ec2.ImportKeyPairOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.ImportKeyPairOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.ImportKeyPairInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_ImportKeyPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportKeyPair'
type EC2Port_ImportKeyPair_Call struct {
	*mock.Call
}

// ImportKeyPair is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.ImportKeyPairInput
func (_e *EC2Port_Expecter) ImportKeyPair(ctx any, input any) *EC2Port_ImportKeyPair_Call {
	return &EC2Port_ImportKeyPair_Call{Call: _e.mock.On("ImportKeyPair", ctx, input)}
}

func (_c *EC2Port_ImportKeyPair_Call) Run(run func(ctx context.Context, input *ec2.ImportKeyPairInput)) *EC2Port_ImportKeyPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.ImportKeyPairInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.ImportKeyPairInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_ImportKeyPair_Call) Return(importKeyPairOutput *ec2.ImportKeyPairOutput, err error) *EC2Port_ImportKeyPair_Call {
	_c.Call.Return(importKeyPairOutput, err)
	return _c
}

func (_c *EC2Port_ImportKeyPair_Call) RunAndReturn(run func(ctx context.Context, input *ec2.ImportKeyPairInput) (*ec2.ImportKeyPairOutput, error)) *EC2Port_ImportKeyPair_Call {
	_c.Call.Return(run)
	return _c
}

// RunInstances provides a mock function for the type EC2Port
func (_mock *EC2Port) RunInstances(ctx context.Context, input *ec2.RunInstancesInput) (*ec2.RunInstancesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RunInstances")
	}

	var r0 *ec2.RunInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.RunInstancesInput) (*ec2.RunInstancesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.RunInstancesInput) *ec2.RunInstancesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.RunInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.RunInstancesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_RunInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInstances'
type EC2Port_RunInstances_Call struct {
	*mock.Call
}

// RunInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.RunInstancesInput
func (_e *EC2Port_Expecter) RunInstances(ctx any, input any) *EC2Port_RunInstances_Call {
	return &EC2Port_RunInstances_Call{Call: _e.mock.On("RunInstances", ctx, input)}
}

func (_c *EC2Port_RunInstances_Call) Run(run func(ctx context.Context, input *ec2.RunInstancesInput)) *EC2Port_RunInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.RunInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.RunInstancesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_RunInstances_Call) Return(runInstancesOutput *ec2.RunInstancesOutput, err error) *EC2Port_RunInstances_Call {
	_c.Call.Return(runInstancesOutput, err)
	return _c
}

func (_c *EC2Port_RunInstances_Call) RunAndReturn(run func(ctx context.Context, input *ec2.RunInstancesInput) (*ec2.RunInstancesOutput, error)) *EC2Port_RunInstances_Call {
	_c.Call.Return(run)
	return _c
}

// StartInstances provides a mock function for the type EC2Port
func (_mock *EC2Port) StartInstances(ctx context.Context, input *ec2.StartInstancesInput) (*ec2.StartInstancesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StartInstances")
	}

	var r0 *ec2.StartInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.StartInstancesInput) (*ec2.StartInstancesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.StartInstancesInput) *ec2.StartInstancesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.StartInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.StartInstancesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_StartInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartInstances'
type EC2Port_StartInstances_Call struct {
	*mock.Call
}

// StartInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.StartInstancesInput
func (_e *EC2Port_Expecter) StartInstances(ctx any, input any) *EC2Port_StartInstances_Call {
	return &EC2Port_StartInstances_Call{Call: _e.mock.On("StartInstances", ctx, input)}
}

func (_c *EC2Port_StartInstances_Call) Run(run func(ctx context.Context, input *ec2.StartInstancesInput)) *EC2Port_StartInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.StartInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.StartInstancesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_StartInstances_Call) Return(startInstancesOutput *ec2.StartInstancesOutput, err error) *EC2Port_StartInstances_Call {
	_c.Call.Return(startInstancesOutput, err)
	return _c
}

func (_c *EC2Port_StartInstances_Call) RunAndReturn(run func(ctx context.Context, input *ec2.StartInstancesInput) (*ec2.StartInstancesOutput, error)) *EC2Port_StartInstances_Call {
	_c.Call.Return(run)
	return _c
}

// StopInstances provides a mock function for the type EC2Port
func (_mock *EC2Port) StopInstances(ctx context.Context, input *ec2.StopInstancesInput) (*ec2.StopInstancesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StopInstances")
	}

	var r0 *ec2.StopInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.StopInstancesInput) (*ec2.StopInstancesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.StopInstancesInput) *ec2.StopInstancesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.StopInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.StopInstancesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_StopInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopInstances'
type EC2Port_StopInstances_Call struct {
	*mock.Call
}

// StopInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.StopInstancesInput
func (_e *EC2Port_Expecter) StopInstances(ctx any, input any) *EC2Port_StopInstances_Call {
	return &EC2Port_StopInstances_Call{Call: _e.mock.On("StopInstances", ctx, input)}
}

func (_c *EC2Port_StopInstances_Call) Run(run func(ctx context.Context, input *ec2.StopInstancesInput)) *EC2Port_StopInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.StopInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.StopInstancesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_StopInstances_Call) Return(stopInstancesOutput *ec2.StopInstancesOutput, err error) *EC2Port_StopInstances_Call {
	_c.Call.Return(stopInstancesOutput, err)
	return _c
}

func (_c *EC2Port_StopInstances_Call) RunAndReturn(run func(ctx context.Context, input *ec2.StopInstancesInput) (*ec2.StopInstancesOutput, error)) *EC2Port_StopInstances_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateInstances provides a mock function for the type EC2Port
func (_mock *EC2Port) TerminateInstances(ctx context.Context, input *ec2.TerminateInstancesInput) (*ec2.TerminateInstancesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TerminateInstances")
	}

	var r0 *ec2.TerminateInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.TerminateInstancesInput) (*ec2.TerminateInstancesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ec2.TerminateInstancesInput) *ec2.TerminateInstancesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.TerminateInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ec2.TerminateInstancesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EC2Port_TerminateInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateInstances'
type EC2Port_TerminateInstances_Call struct {
	*mock.Call
}

// TerminateInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ec2.TerminateInstancesInput
func (_e *EC2Port_Expecter) TerminateInstances(ctx any, input any) *EC2Port_TerminateInstances_Call {
	return &EC2Port_TerminateInstances_Call{Call: _e.mock.On("TerminateInstances", ctx, input)}
}

func (_c *EC2Port_TerminateInstances_Call) Run(run func(ctx context.Context, input *ec2.TerminateInstancesInput)) *EC2Port_TerminateInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ec2.TerminateInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*ec2.TerminateInstancesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EC2Port_TerminateInstances_Call) Return(terminateInstancesOutput *ec2.TerminateInstancesOutput, err error) *EC2Port_TerminateInstances_Call {
	_c.Call.Return(terminateInstancesOutput, err)
	return _c
}

func (_c *EC2Port_TerminateInstances_Call) RunAndReturn(run func(ctx context.Context, input *ec2.TerminateInstancesInput) (*ec2.TerminateInstancesOutput, error)) *EC2Port_TerminateInstances_Call {
	_c.Call.Return(run)
	return _c
}
