// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/my-devstack/mydevstack/pkg/proxy/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewGitHubClientPort creates a new instance of GitHubClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitHubClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitHubClientPort {
	mock := &GitHubClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitHubClientPort is an autogenerated mock type for the GitHubClientPort type
type GitHubClientPort struct {
	mock.Mock
}

type GitHubClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *GitHubClientPort) EXPECT() *GitHubClientPort_Expecter {
	return &GitHubClientPort_Expecter{mock: &_m.Mock}
}

// GetLatestRelease provides a mock function for the type GitHubClientPort
func (_mock *GitHubClientPort) GetLatestRelease(ctx context.Context, repoURL string) (*ports.Release, error) {
	ret := _mock.Called(ctx, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRelease")
	}

	var r0 *ports.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ports.Release, error)); ok {
		return returnFunc(ctx, repoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ports.Release); ok {
		r0 = returnFunc(ctx, repoURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GitHubClientPort_GetLatestRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRelease'
type GitHubClientPort_GetLatestRelease_Call struct {
	*mock.Call
}

// GetLatestRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - repoURL string
func (_e *GitHubClientPort_Expecter) GetLatestRelease(ctx interface{}, repoURL interface{}) *GitHubClientPort_GetLatestRelease_Call {
	return &GitHubClientPort_GetLatestRelease_Call{Call: _e.mock.On("GetLatestRelease", ctx, repoURL)}
}

func (_c *GitHubClientPort_GetLatestRelease_Call) Run(run func(ctx context.Context, repoURL string)) *GitHubClientPort_GetLatestRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GitHubClientPort_GetLatestRelease_Call) Return(release *ports.Release, err error) *GitHubClientPort_GetLatestRelease_Call {
	_c.Call.Return(release, err)
	return _c
}

func (_c *GitHubClientPort_GetLatestRelease_Call) RunAndReturn(run func(ctx context.Context, repoURL string) (*ports.Release, error)) *GitHubClientPort_GetLatestRelease_Call {
	_c.Call.Return(run)
	return _c
}
