// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kafka"
	mock "github.com/stretchr/testify/mock"
)

// NewMSKPort creates a new instance of MSKPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMSKPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MSKPort {
	mock := &MSKPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MSKPort is an autogenerated mock type for the MSKPort type
type MSKPort struct {
	mock.Mock
}

type MSKPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MSKPort) EXPECT() *MSKPort_Expecter {
	return &MSKPort_Expecter{mock: &_m.Mock}
}

// CreateClusterV2 provides a mock function for the type MSKPort
func (_mock *MSKPort) CreateClusterV2(ctx context.Context, input *kafka.CreateClusterV2Input) (*kafka.CreateClusterV2Output, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterV2")
	}

	var r0 *kafka.CreateClusterV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.CreateClusterV2Input) (*kafka.CreateClusterV2Output, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.CreateClusterV2Input) *kafka.CreateClusterV2Output); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.CreateClusterV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kafka.CreateClusterV2Input) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MSKPort_CreateClusterV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterV2'
type MSKPort_CreateClusterV2_Call struct {
	*mock.Call
}

// CreateClusterV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kafka.CreateClusterV2Input
func (_e *MSKPort_Expecter) CreateClusterV2(ctx any, input any) *MSKPort_CreateClusterV2_Call {
	return &MSKPort_CreateClusterV2_Call{Call: _e.mock.On("CreateClusterV2", ctx, input)}
}

func (_c *MSKPort_CreateClusterV2_Call) Run(run func(ctx context.Context, input *kafka.CreateClusterV2Input)) *MSKPort_CreateClusterV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.CreateClusterV2Input
		if args[1] != nil {
			arg1 = args[1].(*kafka.CreateClusterV2Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MSKPort_CreateClusterV2_Call) Return(createClusterV2Output *kafka.CreateClusterV2Output, err error) *MSKPort_CreateClusterV2_Call {
	_c.Call.Return(createClusterV2Output, err)
	return _c
}

func (_c *MSKPort_CreateClusterV2_Call) RunAndReturn(run func(ctx context.Context, input *kafka.CreateClusterV2Input) (*kafka.CreateClusterV2Output, error)) *MSKPort_CreateClusterV2_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCluster provides a mock function for the type MSKPort
func (_mock *MSKPort) DeleteCluster(ctx context.Context, input *kafka.DeleteClusterInput) (*kafka.DeleteClusterOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 *kafka.DeleteClusterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.DeleteClusterInput) (*kafka.DeleteClusterOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.DeleteClusterInput) *kafka.DeleteClusterOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.DeleteClusterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kafka.DeleteClusterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MSKPort_DeleteCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCluster'
type MSKPort_DeleteCluster_Call struct {
	*mock.Call
}

// DeleteCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kafka.DeleteClusterInput
func (_e *MSKPort_Expecter) DeleteCluster(ctx any, input any) *MSKPort_DeleteCluster_Call {
	return &MSKPort_DeleteCluster_Call{Call: _e.mock.On("DeleteCluster", ctx, input)}
}

func (_c *MSKPort_DeleteCluster_Call) Run(run func(ctx context.Context, input *kafka.DeleteClusterInput)) *MSKPort_DeleteCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.DeleteClusterInput
		if args[1] != nil {
			arg1 = args[1].(*kafka.DeleteClusterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MSKPort_DeleteCluster_Call) Return(deleteClusterOutput *kafka.DeleteClusterOutput, err error) *MSKPort_DeleteCluster_Call {
	_c.Call.Return(deleteClusterOutput, err)
	return _c
}

func (_c *MSKPort_DeleteCluster_Call) RunAndReturn(run func(ctx context.Context, input *kafka.DeleteClusterInput) (*kafka.DeleteClusterOutput, error)) *MSKPort_DeleteCluster_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeClusterV2 provides a mock function for the type MSKPort
func (_mock *MSKPort) DescribeClusterV2(ctx context.Context, input *kafka.DescribeClusterV2Input) (*kafka.DescribeClusterV2Output, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeClusterV2")
	}

	var r0 *kafka.DescribeClusterV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.DescribeClusterV2Input) (*kafka.DescribeClusterV2Output, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.DescribeClusterV2Input) *kafka.DescribeClusterV2Output); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.DescribeClusterV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kafka.DescribeClusterV2Input) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MSKPort_DescribeClusterV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeClusterV2'
type MSKPort_DescribeClusterV2_Call struct {
	*mock.Call
}

// DescribeClusterV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kafka.DescribeClusterV2Input
func (_e *MSKPort_Expecter) DescribeClusterV2(ctx any, input any) *MSKPort_DescribeClusterV2_Call {
	return &MSKPort_DescribeClusterV2_Call{Call: _e.mock.On("DescribeClusterV2", ctx, input)}
}

func (_c *MSKPort_DescribeClusterV2_Call) Run(run func(ctx context.Context, input *kafka.DescribeClusterV2Input)) *MSKPort_DescribeClusterV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.DescribeClusterV2Input
		if args[1] != nil {
			arg1 = args[1].(*kafka.DescribeClusterV2Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MSKPort_DescribeClusterV2_Call) Return(describeClusterV2Output *kafka.DescribeClusterV2Output, err error) *MSKPort_DescribeClusterV2_Call {
	_c.Call.Return(describeClusterV2Output, err)
	return _c
}

func (_c *MSKPort_DescribeClusterV2_Call) RunAndReturn(run func(ctx context.Context, input *kafka.DescribeClusterV2Input) (*kafka.DescribeClusterV2Output, error)) *MSKPort_DescribeClusterV2_Call {
	_c.Call.Return(run)
	return _c
}

// GetBootstrapBrokers provides a mock function for the type MSKPort
func (_mock *MSKPort) GetBootstrapBrokers(ctx context.Context, input *kafka.GetBootstrapBrokersInput) (*kafka.GetBootstrapBrokersOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetBootstrapBrokers")
	}

	var r0 *kafka.GetBootstrapBrokersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.GetBootstrapBrokersInput) (*kafka.GetBootstrapBrokersOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.GetBootstrapBrokersInput) *kafka.GetBootstrapBrokersOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.GetBootstrapBrokersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kafka.GetBootstrapBrokersInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MSKPort_GetBootstrapBrokers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBootstrapBrokers'
type MSKPort_GetBootstrapBrokers_Call struct {
	*mock.Call
}

// GetBootstrapBrokers is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kafka.GetBootstrapBrokersInput
func (_e *MSKPort_Expecter) GetBootstrapBrokers(ctx any, input any) *MSKPort_GetBootstrapBrokers_Call {
	return &MSKPort_GetBootstrapBrokers_Call{Call: _e.mock.On("GetBootstrapBrokers", ctx, input)}
}

func (_c *MSKPort_GetBootstrapBrokers_Call) Run(run func(ctx context.Context, input *kafka.GetBootstrapBrokersInput)) *MSKPort_GetBootstrapBrokers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.GetBootstrapBrokersInput
		if args[1] != nil {
			arg1 = args[1].(*kafka.GetBootstrapBrokersInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MSKPort_GetBootstrapBrokers_Call) Return(getBootstrapBrokersOutput *kafka.GetBootstrapBrokersOutput, err error) *MSKPort_GetBootstrapBrokers_Call {
	_c.Call.Return(getBootstrapBrokersOutput, err)
	return _c
}

func (_c *MSKPort_GetBootstrapBrokers_Call) RunAndReturn(run func(ctx context.Context, input *kafka.GetBootstrapBrokersInput) (*kafka.GetBootstrapBrokersOutput, error)) *MSKPort_GetBootstrapBrokers_Call {
	_c.Call.Return(run)
	return _c
}

// ListClustersV2 provides a mock function for the type MSKPort
func (_mock *MSKPort) ListClustersV2(ctx context.Context, input *kafka.ListClustersV2Input) (*kafka.ListClustersV2Output, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListClustersV2")
	}

	var r0 *kafka.ListClustersV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.ListClustersV2Input) (*kafka.ListClustersV2Output, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kafka.ListClustersV2Input) *kafka.ListClustersV2Output); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.ListClustersV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kafka.ListClustersV2Input) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MSKPort_ListClustersV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClustersV2'
type MSKPort_ListClustersV2_Call struct {
	*mock.Call
}

// ListClustersV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kafka.ListClustersV2Input
func (_e *MSKPort_Expecter) ListClustersV2(ctx any, input any) *MSKPort_ListClustersV2_Call {
	return &MSKPort_ListClustersV2_Call{Call: _e.mock.On("ListClustersV2", ctx, input)}
}

func (_c *MSKPort_ListClustersV2_Call) Run(run func(ctx context.Context, input *kafka.ListClustersV2Input)) *MSKPort_ListClustersV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kafka.ListClustersV2Input
		if args[1] != nil {
			arg1 = args[1].(*kafka.ListClustersV2Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MSKPort_ListClustersV2_Call) Return(listClustersV2Output *kafka.ListClustersV2Output, err error) *MSKPort_ListClustersV2_Call {
	_c.Call.Return(listClustersV2Output, err)
	return _c
}

func (_c *MSKPort_ListClustersV2_Call) RunAndReturn(run func(ctx context.Context, input *kafka.ListClustersV2Input) (*kafka.ListClustersV2Output, error)) *MSKPort_ListClustersV2_Call {
	_c.Call.Return(run)
	return _c
}
