// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/opensearch"
	mock "github.com/stretchr/testify/mock"
)

// NewOpenSearchPort creates a new instance of OpenSearchPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpenSearchPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpenSearchPort {
	mock := &OpenSearchPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OpenSearchPort is an autogenerated mock type for the OpenSearchPort type
type OpenSearchPort struct {
	mock.Mock
}

type OpenSearchPort_Expecter struct {
	mock *mock.Mock
}

func (_m *OpenSearchPort) EXPECT() *OpenSearchPort_Expecter {
	return &OpenSearchPort_Expecter{mock: &_m.Mock}
}

// AddTags provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) AddTags(ctx context.Context, input *opensearch.AddTagsInput) (*opensearch.AddTagsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddTags")
	}

	var r0 *opensearch.AddTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.AddTagsInput) (*opensearch.AddTagsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.AddTagsInput) *opensearch.AddTagsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.AddTagsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.AddTagsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_AddTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTags'
type OpenSearchPort_AddTags_Call struct {
	*mock.Call
}

// AddTags is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.AddTagsInput
func (_e *OpenSearchPort_Expecter) AddTags(ctx interface{}, input interface{}) *OpenSearchPort_AddTags_Call {
	return &OpenSearchPort_AddTags_Call{Call: _e.mock.On("AddTags", ctx, input)}
}

func (_c *OpenSearchPort_AddTags_Call) Run(run func(ctx context.Context, input *opensearch.AddTagsInput)) *OpenSearchPort_AddTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.AddTagsInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.AddTagsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_AddTags_Call) Return(addTagsOutput *opensearch.AddTagsOutput, err error) *OpenSearchPort_AddTags_Call {
	_c.Call.Return(addTagsOutput, err)
	return _c
}

func (_c *OpenSearchPort_AddTags_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.AddTagsInput) (*opensearch.AddTagsOutput, error)) *OpenSearchPort_AddTags_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDomain provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) CreateDomain(ctx context.Context, input *opensearch.CreateDomainInput) (*opensearch.CreateDomainOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateDomain")
	}

	var r0 *opensearch.CreateDomainOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.CreateDomainInput) (*opensearch.CreateDomainOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.CreateDomainInput) *opensearch.CreateDomainOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.CreateDomainOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.CreateDomainInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_CreateDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDomain'
type OpenSearchPort_CreateDomain_Call struct {
	*mock.Call
}

// CreateDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.CreateDomainInput
func (_e *OpenSearchPort_Expecter) CreateDomain(ctx interface{}, input interface{}) *OpenSearchPort_CreateDomain_Call {
	return &OpenSearchPort_CreateDomain_Call{Call: _e.mock.On("CreateDomain", ctx, input)}
}

func (_c *OpenSearchPort_CreateDomain_Call) Run(run func(ctx context.Context, input *opensearch.CreateDomainInput)) *OpenSearchPort_CreateDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.CreateDomainInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.CreateDomainInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_CreateDomain_Call) Return(createDomainOutput *opensearch.CreateDomainOutput, err error) *OpenSearchPort_CreateDomain_Call {
	_c.Call.Return(createDomainOutput, err)
	return _c
}

func (_c *OpenSearchPort_CreateDomain_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.CreateDomainInput) (*opensearch.CreateDomainOutput, error)) *OpenSearchPort_CreateDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDomain provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) DeleteDomain(ctx context.Context, input *opensearch.DeleteDomainInput) (*opensearch.DeleteDomainOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDomain")
	}

	var r0 *opensearch.DeleteDomainOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DeleteDomainInput) (*opensearch.DeleteDomainOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DeleteDomainInput) *opensearch.DeleteDomainOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.DeleteDomainOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.DeleteDomainInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_DeleteDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDomain'
type OpenSearchPort_DeleteDomain_Call struct {
	*mock.Call
}

// DeleteDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.DeleteDomainInput
func (_e *OpenSearchPort_Expecter) DeleteDomain(ctx interface{}, input interface{}) *OpenSearchPort_DeleteDomain_Call {
	return &OpenSearchPort_DeleteDomain_Call{Call: _e.mock.On("DeleteDomain", ctx, input)}
}

func (_c *OpenSearchPort_DeleteDomain_Call) Run(run func(ctx context.Context, input *opensearch.DeleteDomainInput)) *OpenSearchPort_DeleteDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.DeleteDomainInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.DeleteDomainInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_DeleteDomain_Call) Return(deleteDomainOutput *opensearch.DeleteDomainOutput, err error) *OpenSearchPort_DeleteDomain_Call {
	_c.Call.Return(deleteDomainOutput, err)
	return _c
}

func (_c *OpenSearchPort_DeleteDomain_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.DeleteDomainInput) (*opensearch.DeleteDomainOutput, error)) *OpenSearchPort_DeleteDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeDomain provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) DescribeDomain(ctx context.Context, input *opensearch.DescribeDomainInput) (*opensearch.DescribeDomainOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeDomain")
	}

	var r0 *opensearch.DescribeDomainOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainInput) (*opensearch.DescribeDomainOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainInput) *opensearch.DescribeDomainOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.DescribeDomainOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.DescribeDomainInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_DescribeDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDomain'
type OpenSearchPort_DescribeDomain_Call struct {
	*mock.Call
}

// DescribeDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.DescribeDomainInput
func (_e *OpenSearchPort_Expecter) DescribeDomain(ctx interface{}, input interface{}) *OpenSearchPort_DescribeDomain_Call {
	return &OpenSearchPort_DescribeDomain_Call{Call: _e.mock.On("DescribeDomain", ctx, input)}
}

func (_c *OpenSearchPort_DescribeDomain_Call) Run(run func(ctx context.Context, input *opensearch.DescribeDomainInput)) *OpenSearchPort_DescribeDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.DescribeDomainInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.DescribeDomainInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_DescribeDomain_Call) Return(describeDomainOutput *opensearch.DescribeDomainOutput, err error) *OpenSearchPort_DescribeDomain_Call {
	_c.Call.Return(describeDomainOutput, err)
	return _c
}

func (_c *OpenSearchPort_DescribeDomain_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.DescribeDomainInput) (*opensearch.DescribeDomainOutput, error)) *OpenSearchPort_DescribeDomain_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeDomainConfig provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) DescribeDomainConfig(ctx context.Context, input *opensearch.DescribeDomainConfigInput) (*opensearch.DescribeDomainConfigOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeDomainConfig")
	}

	var r0 *opensearch.DescribeDomainConfigOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainConfigInput) (*opensearch.DescribeDomainConfigOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.DescribeDomainConfigInput) *opensearch.DescribeDomainConfigOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.DescribeDomainConfigOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.DescribeDomainConfigInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_DescribeDomainConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDomainConfig'
type OpenSearchPort_DescribeDomainConfig_Call struct {
	*mock.Call
}

// DescribeDomainConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.DescribeDomainConfigInput
func (_e *OpenSearchPort_Expecter) DescribeDomainConfig(ctx interface{}, input interface{}) *OpenSearchPort_DescribeDomainConfig_Call {
	return &OpenSearchPort_DescribeDomainConfig_Call{Call: _e.mock.On("DescribeDomainConfig", ctx, input)}
}

func (_c *OpenSearchPort_DescribeDomainConfig_Call) Run(run func(ctx context.Context, input *opensearch.DescribeDomainConfigInput)) *OpenSearchPort_DescribeDomainConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.DescribeDomainConfigInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.DescribeDomainConfigInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_DescribeDomainConfig_Call) Return(describeDomainConfigOutput *opensearch.DescribeDomainConfigOutput, err error) *OpenSearchPort_DescribeDomainConfig_Call {
	_c.Call.Return(describeDomainConfigOutput, err)
	return _c
}

func (_c *OpenSearchPort_DescribeDomainConfig_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.DescribeDomainConfigInput) (*opensearch.DescribeDomainConfigOutput, error)) *OpenSearchPort_DescribeDomainConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompatibleVersions provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) GetCompatibleVersions(ctx context.Context, input *opensearch.GetCompatibleVersionsInput) (*opensearch.GetCompatibleVersionsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetCompatibleVersions")
	}

	var r0 *opensearch.GetCompatibleVersionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.GetCompatibleVersionsInput) (*opensearch.GetCompatibleVersionsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.GetCompatibleVersionsInput) *opensearch.GetCompatibleVersionsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.GetCompatibleVersionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.GetCompatibleVersionsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_GetCompatibleVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompatibleVersions'
type OpenSearchPort_GetCompatibleVersions_Call struct {
	*mock.Call
}

// GetCompatibleVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.GetCompatibleVersionsInput
func (_e *OpenSearchPort_Expecter) GetCompatibleVersions(ctx interface{}, input interface{}) *OpenSearchPort_GetCompatibleVersions_Call {
	return &OpenSearchPort_GetCompatibleVersions_Call{Call: _e.mock.On("GetCompatibleVersions", ctx, input)}
}

func (_c *OpenSearchPort_GetCompatibleVersions_Call) Run(run func(ctx context.Context, input *opensearch.GetCompatibleVersionsInput)) *OpenSearchPort_GetCompatibleVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.GetCompatibleVersionsInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.GetCompatibleVersionsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_GetCompatibleVersions_Call) Return(getCompatibleVersionsOutput *opensearch.GetCompatibleVersionsOutput, err error) *OpenSearchPort_GetCompatibleVersions_Call {
	_c.Call.Return(getCompatibleVersionsOutput, err)
	return _c
}

func (_c *OpenSearchPort_GetCompatibleVersions_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.GetCompatibleVersionsInput) (*opensearch.GetCompatibleVersionsOutput, error)) *OpenSearchPort_GetCompatibleVersions_Call {
	_c.Call.Return(run)
	return _c
}

// ListDomainNames provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) ListDomainNames(ctx context.Context, input *opensearch.ListDomainNamesInput) (*opensearch.ListDomainNamesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListDomainNames")
	}

	var r0 *opensearch.ListDomainNamesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListDomainNamesInput) (*opensearch.ListDomainNamesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListDomainNamesInput) *opensearch.ListDomainNamesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.ListDomainNamesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.ListDomainNamesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_ListDomainNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDomainNames'
type OpenSearchPort_ListDomainNames_Call struct {
	*mock.Call
}

// ListDomainNames is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.ListDomainNamesInput
func (_e *OpenSearchPort_Expecter) ListDomainNames(ctx interface{}, input interface{}) *OpenSearchPort_ListDomainNames_Call {
	return &OpenSearchPort_ListDomainNames_Call{Call: _e.mock.On("ListDomainNames", ctx, input)}
}

func (_c *OpenSearchPort_ListDomainNames_Call) Run(run func(ctx context.Context, input *opensearch.ListDomainNamesInput)) *OpenSearchPort_ListDomainNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.ListDomainNamesInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.ListDomainNamesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_ListDomainNames_Call) Return(listDomainNamesOutput *opensearch.ListDomainNamesOutput, err error) *OpenSearchPort_ListDomainNames_Call {
	_c.Call.Return(listDomainNamesOutput, err)
	return _c
}

func (_c *OpenSearchPort_ListDomainNames_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.ListDomainNamesInput) (*opensearch.ListDomainNamesOutput, error)) *OpenSearchPort_ListDomainNames_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) ListTags(ctx context.Context, input *opensearch.ListTagsInput) (*opensearch.ListTagsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 *opensearch.ListTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListTagsInput) (*opensearch.ListTagsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.ListTagsInput) *opensearch.ListTagsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.ListTagsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.ListTagsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type OpenSearchPort_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.ListTagsInput
func (_e *OpenSearchPort_Expecter) ListTags(ctx interface{}, input interface{}) *OpenSearchPort_ListTags_Call {
	return &OpenSearchPort_ListTags_Call{Call: _e.mock.On("ListTags", ctx, input)}
}

func (_c *OpenSearchPort_ListTags_Call) Run(run func(ctx context.Context, input *opensearch.ListTagsInput)) *OpenSearchPort_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.ListTagsInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.ListTagsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_ListTags_Call) Return(listTagsOutput *opensearch.ListTagsOutput, err error) *OpenSearchPort_ListTags_Call {
	_c.Call.Return(listTagsOutput, err)
	return _c
}

func (_c *OpenSearchPort_ListTags_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.ListTagsInput) (*opensearch.ListTagsOutput, error)) *OpenSearchPort_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTags provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) RemoveTags(ctx context.Context, input *opensearch.RemoveTagsInput) (*opensearch.RemoveTagsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTags")
	}

	var r0 *opensearch.RemoveTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.RemoveTagsInput) (*opensearch.RemoveTagsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.RemoveTagsInput) *opensearch.RemoveTagsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.RemoveTagsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.RemoveTagsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_RemoveTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTags'
type OpenSearchPort_RemoveTags_Call struct {
	*mock.Call
}

// RemoveTags is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.RemoveTagsInput
func (_e *OpenSearchPort_Expecter) RemoveTags(ctx interface{}, input interface{}) *OpenSearchPort_RemoveTags_Call {
	return &OpenSearchPort_RemoveTags_Call{Call: _e.mock.On("RemoveTags", ctx, input)}
}

func (_c *OpenSearchPort_RemoveTags_Call) Run(run func(ctx context.Context, input *opensearch.RemoveTagsInput)) *OpenSearchPort_RemoveTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.RemoveTagsInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.RemoveTagsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_RemoveTags_Call) Return(removeTagsOutput *opensearch.RemoveTagsOutput, err error) *OpenSearchPort_RemoveTags_Call {
	_c.Call.Return(removeTagsOutput, err)
	return _c
}

func (_c *OpenSearchPort_RemoveTags_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.RemoveTagsInput) (*opensearch.RemoveTagsOutput, error)) *OpenSearchPort_RemoveTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDomainConfig provides a mock function for the type OpenSearchPort
func (_mock *OpenSearchPort) UpdateDomainConfig(ctx context.Context, input *opensearch.UpdateDomainConfigInput) (*opensearch.UpdateDomainConfigOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDomainConfig")
	}

	var r0 *opensearch.UpdateDomainConfigOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.UpdateDomainConfigInput) (*opensearch.UpdateDomainConfigOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opensearch.UpdateDomainConfigInput) *opensearch.UpdateDomainConfigOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opensearch.UpdateDomainConfigOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opensearch.UpdateDomainConfigInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OpenSearchPort_UpdateDomainConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDomainConfig'
type OpenSearchPort_UpdateDomainConfig_Call struct {
	*mock.Call
}

// UpdateDomainConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - input *opensearch.UpdateDomainConfigInput
func (_e *OpenSearchPort_Expecter) UpdateDomainConfig(ctx interface{}, input interface{}) *OpenSearchPort_UpdateDomainConfig_Call {
	return &OpenSearchPort_UpdateDomainConfig_Call{Call: _e.mock.On("UpdateDomainConfig", ctx, input)}
}

func (_c *OpenSearchPort_UpdateDomainConfig_Call) Run(run func(ctx context.Context, input *opensearch.UpdateDomainConfigInput)) *OpenSearchPort_UpdateDomainConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opensearch.UpdateDomainConfigInput
		if args[1] != nil {
			arg1 = args[1].(*opensearch.UpdateDomainConfigInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OpenSearchPort_UpdateDomainConfig_Call) Return(updateDomainConfigOutput *opensearch.UpdateDomainConfigOutput, err error) *OpenSearchPort_UpdateDomainConfig_Call {
	_c.Call.Return(updateDomainConfigOutput, err)
	return _c
}

func (_c *OpenSearchPort_UpdateDomainConfig_Call) RunAndReturn(run func(ctx context.Context, input *opensearch.UpdateDomainConfigInput) (*opensearch.UpdateDomainConfigOutput, error)) *OpenSearchPort_UpdateDomainConfig_Call {
	_c.Call.Return(run)
	return _c
}
