// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sfn"
	mock "github.com/stretchr/testify/mock"
)

// NewStepFunctionsPort creates a new instance of StepFunctionsPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStepFunctionsPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *StepFunctionsPort {
	mock := &StepFunctionsPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StepFunctionsPort is an autogenerated mock type for the StepFunctionsPort type
type StepFunctionsPort struct {
	mock.Mock
}

type StepFunctionsPort_Expecter struct {
	mock *mock.Mock
}

func (_m *StepFunctionsPort) EXPECT() *StepFunctionsPort_Expecter {
	return &StepFunctionsPort_Expecter{mock: &_m.Mock}
}

// CreateStateMachine provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) CreateStateMachine(ctx context.Context, input *sfn.CreateStateMachineInput) (*sfn.CreateStateMachineOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateStateMachine")
	}

	var r0 *sfn.CreateStateMachineOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.CreateStateMachineInput) (*sfn.CreateStateMachineOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.CreateStateMachineInput) *sfn.CreateStateMachineOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.CreateStateMachineOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.CreateStateMachineInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_CreateStateMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStateMachine'
type StepFunctionsPort_CreateStateMachine_Call struct {
	*mock.Call
}

// CreateStateMachine is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.CreateStateMachineInput
func (_e *StepFunctionsPort_Expecter) CreateStateMachine(ctx interface{}, input interface{}) *StepFunctionsPort_CreateStateMachine_Call {
	return &StepFunctionsPort_CreateStateMachine_Call{Call: _e.mock.On("CreateStateMachine", ctx, input)}
}

func (_c *StepFunctionsPort_CreateStateMachine_Call) Run(run func(ctx context.Context, input *sfn.CreateStateMachineInput)) *StepFunctionsPort_CreateStateMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.CreateStateMachineInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.CreateStateMachineInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_CreateStateMachine_Call) Return(createStateMachineOutput *sfn.CreateStateMachineOutput, err error) *StepFunctionsPort_CreateStateMachine_Call {
	_c.Call.Return(createStateMachineOutput, err)
	return _c
}

func (_c *StepFunctionsPort_CreateStateMachine_Call) RunAndReturn(run func(ctx context.Context, input *sfn.CreateStateMachineInput) (*sfn.CreateStateMachineOutput, error)) *StepFunctionsPort_CreateStateMachine_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStateMachine provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) DeleteStateMachine(ctx context.Context, input *sfn.DeleteStateMachineInput) (*sfn.DeleteStateMachineOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStateMachine")
	}

	var r0 *sfn.DeleteStateMachineOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DeleteStateMachineInput) (*sfn.DeleteStateMachineOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DeleteStateMachineInput) *sfn.DeleteStateMachineOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.DeleteStateMachineOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.DeleteStateMachineInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_DeleteStateMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStateMachine'
type StepFunctionsPort_DeleteStateMachine_Call struct {
	*mock.Call
}

// DeleteStateMachine is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.DeleteStateMachineInput
func (_e *StepFunctionsPort_Expecter) DeleteStateMachine(ctx interface{}, input interface{}) *StepFunctionsPort_DeleteStateMachine_Call {
	return &StepFunctionsPort_DeleteStateMachine_Call{Call: _e.mock.On("DeleteStateMachine", ctx, input)}
}

func (_c *StepFunctionsPort_DeleteStateMachine_Call) Run(run func(ctx context.Context, input *sfn.DeleteStateMachineInput)) *StepFunctionsPort_DeleteStateMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.DeleteStateMachineInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.DeleteStateMachineInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_DeleteStateMachine_Call) Return(deleteStateMachineOutput *sfn.DeleteStateMachineOutput, err error) *StepFunctionsPort_DeleteStateMachine_Call {
	_c.Call.Return(deleteStateMachineOutput, err)
	return _c
}

func (_c *StepFunctionsPort_DeleteStateMachine_Call) RunAndReturn(run func(ctx context.Context, input *sfn.DeleteStateMachineInput) (*sfn.DeleteStateMachineOutput, error)) *StepFunctionsPort_DeleteStateMachine_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeExecution provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) DescribeExecution(ctx context.Context, input *sfn.DescribeExecutionInput) (*sfn.DescribeExecutionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeExecution")
	}

	var r0 *sfn.DescribeExecutionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DescribeExecutionInput) (*sfn.DescribeExecutionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DescribeExecutionInput) *sfn.DescribeExecutionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.DescribeExecutionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.DescribeExecutionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_DescribeExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeExecution'
type StepFunctionsPort_DescribeExecution_Call struct {
	*mock.Call
}

// DescribeExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.DescribeExecutionInput
func (_e *StepFunctionsPort_Expecter) DescribeExecution(ctx interface{}, input interface{}) *StepFunctionsPort_DescribeExecution_Call {
	return &StepFunctionsPort_DescribeExecution_Call{Call: _e.mock.On("DescribeExecution", ctx, input)}
}

func (_c *StepFunctionsPort_DescribeExecution_Call) Run(run func(ctx context.Context, input *sfn.DescribeExecutionInput)) *StepFunctionsPort_DescribeExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.DescribeExecutionInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.DescribeExecutionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_DescribeExecution_Call) Return(describeExecutionOutput *sfn.DescribeExecutionOutput, err error) *StepFunctionsPort_DescribeExecution_Call {
	_c.Call.Return(describeExecutionOutput, err)
	return _c
}

func (_c *StepFunctionsPort_DescribeExecution_Call) RunAndReturn(run func(ctx context.Context, input *sfn.DescribeExecutionInput) (*sfn.DescribeExecutionOutput, error)) *StepFunctionsPort_DescribeExecution_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeStateMachine provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) DescribeStateMachine(ctx context.Context, input *sfn.DescribeStateMachineInput) (*sfn.DescribeStateMachineOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeStateMachine")
	}

	var r0 *sfn.DescribeStateMachineOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DescribeStateMachineInput) (*sfn.DescribeStateMachineOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.DescribeStateMachineInput) *sfn.DescribeStateMachineOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.DescribeStateMachineOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.DescribeStateMachineInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_DescribeStateMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeStateMachine'
type StepFunctionsPort_DescribeStateMachine_Call struct {
	*mock.Call
}

// DescribeStateMachine is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.DescribeStateMachineInput
func (_e *StepFunctionsPort_Expecter) DescribeStateMachine(ctx interface{}, input interface{}) *StepFunctionsPort_DescribeStateMachine_Call {
	return &StepFunctionsPort_DescribeStateMachine_Call{Call: _e.mock.On("DescribeStateMachine", ctx, input)}
}

func (_c *StepFunctionsPort_DescribeStateMachine_Call) Run(run func(ctx context.Context, input *sfn.DescribeStateMachineInput)) *StepFunctionsPort_DescribeStateMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.DescribeStateMachineInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.DescribeStateMachineInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_DescribeStateMachine_Call) Return(describeStateMachineOutput *sfn.DescribeStateMachineOutput, err error) *StepFunctionsPort_DescribeStateMachine_Call {
	_c.Call.Return(describeStateMachineOutput, err)
	return _c
}

func (_c *StepFunctionsPort_DescribeStateMachine_Call) RunAndReturn(run func(ctx context.Context, input *sfn.DescribeStateMachineInput) (*sfn.DescribeStateMachineOutput, error)) *StepFunctionsPort_DescribeStateMachine_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionHistory provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) GetExecutionHistory(ctx context.Context, input *sfn.GetExecutionHistoryInput) (*sfn.GetExecutionHistoryOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionHistory")
	}

	var r0 *sfn.GetExecutionHistoryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.GetExecutionHistoryInput) (*sfn.GetExecutionHistoryOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.GetExecutionHistoryInput) *sfn.GetExecutionHistoryOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.GetExecutionHistoryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.GetExecutionHistoryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_GetExecutionHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionHistory'
type StepFunctionsPort_GetExecutionHistory_Call struct {
	*mock.Call
}

// GetExecutionHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.GetExecutionHistoryInput
func (_e *StepFunctionsPort_Expecter) GetExecutionHistory(ctx interface{}, input interface{}) *StepFunctionsPort_GetExecutionHistory_Call {
	return &StepFunctionsPort_GetExecutionHistory_Call{Call: _e.mock.On("GetExecutionHistory", ctx, input)}
}

func (_c *StepFunctionsPort_GetExecutionHistory_Call) Run(run func(ctx context.Context, input *sfn.GetExecutionHistoryInput)) *StepFunctionsPort_GetExecutionHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.GetExecutionHistoryInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.GetExecutionHistoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_GetExecutionHistory_Call) Return(getExecutionHistoryOutput *sfn.GetExecutionHistoryOutput, err error) *StepFunctionsPort_GetExecutionHistory_Call {
	_c.Call.Return(getExecutionHistoryOutput, err)
	return _c
}

func (_c *StepFunctionsPort_GetExecutionHistory_Call) RunAndReturn(run func(ctx context.Context, input *sfn.GetExecutionHistoryInput) (*sfn.GetExecutionHistoryOutput, error)) *StepFunctionsPort_GetExecutionHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListExecutions provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) ListExecutions(ctx context.Context, input *sfn.ListExecutionsInput) (*sfn.ListExecutionsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListExecutions")
	}

	var r0 *sfn.ListExecutionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListExecutionsInput) (*sfn.ListExecutionsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListExecutionsInput) *sfn.ListExecutionsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.ListExecutionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.ListExecutionsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_ListExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExecutions'
type StepFunctionsPort_ListExecutions_Call struct {
	*mock.Call
}

// ListExecutions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.ListExecutionsInput
func (_e *StepFunctionsPort_Expecter) ListExecutions(ctx interface{}, input interface{}) *StepFunctionsPort_ListExecutions_Call {
	return &StepFunctionsPort_ListExecutions_Call{Call: _e.mock.On("ListExecutions", ctx, input)}
}

func (_c *StepFunctionsPort_ListExecutions_Call) Run(run func(ctx context.Context, input *sfn.ListExecutionsInput)) *StepFunctionsPort_ListExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.ListExecutionsInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.ListExecutionsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_ListExecutions_Call) Return(listExecutionsOutput *sfn.ListExecutionsOutput, err error) *StepFunctionsPort_ListExecutions_Call {
	_c.Call.Return(listExecutionsOutput, err)
	return _c
}

func (_c *StepFunctionsPort_ListExecutions_Call) RunAndReturn(run func(ctx context.Context, input *sfn.ListExecutionsInput) (*sfn.ListExecutionsOutput, error)) *StepFunctionsPort_ListExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// ListStateMachines provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) ListStateMachines(ctx context.Context, input *sfn.ListStateMachinesInput) (*sfn.ListStateMachinesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListStateMachines")
	}

	var r0 *sfn.ListStateMachinesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListStateMachinesInput) (*sfn.ListStateMachinesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListStateMachinesInput) *sfn.ListStateMachinesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.ListStateMachinesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.ListStateMachinesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_ListStateMachines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStateMachines'
type StepFunctionsPort_ListStateMachines_Call struct {
	*mock.Call
}

// ListStateMachines is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.ListStateMachinesInput
func (_e *StepFunctionsPort_Expecter) ListStateMachines(ctx interface{}, input interface{}) *StepFunctionsPort_ListStateMachines_Call {
	return &StepFunctionsPort_ListStateMachines_Call{Call: _e.mock.On("ListStateMachines", ctx, input)}
}

func (_c *StepFunctionsPort_ListStateMachines_Call) Run(run func(ctx context.Context, input *sfn.ListStateMachinesInput)) *StepFunctionsPort_ListStateMachines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.ListStateMachinesInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.ListStateMachinesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_ListStateMachines_Call) Return(listStateMachinesOutput *sfn.ListStateMachinesOutput, err error) *StepFunctionsPort_ListStateMachines_Call {
	_c.Call.Return(listStateMachinesOutput, err)
	return _c
}

func (_c *StepFunctionsPort_ListStateMachines_Call) RunAndReturn(run func(ctx context.Context, input *sfn.ListStateMachinesInput) (*sfn.ListStateMachinesOutput, error)) *StepFunctionsPort_ListStateMachines_Call {
	_c.Call.Return(run)
	return _c
}

// ListTagsForResource provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) ListTagsForResource(ctx context.Context, input *sfn.ListTagsForResourceInput) (*sfn.ListTagsForResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTagsForResource")
	}

	var r0 *sfn.ListTagsForResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListTagsForResourceInput) (*sfn.ListTagsForResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.ListTagsForResourceInput) *sfn.ListTagsForResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.ListTagsForResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.ListTagsForResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_ListTagsForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTagsForResource'
type StepFunctionsPort_ListTagsForResource_Call struct {
	*mock.Call
}

// ListTagsForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.ListTagsForResourceInput
func (_e *StepFunctionsPort_Expecter) ListTagsForResource(ctx interface{}, input interface{}) *StepFunctionsPort_ListTagsForResource_Call {
	return &StepFunctionsPort_ListTagsForResource_Call{Call: _e.mock.On("ListTagsForResource", ctx, input)}
}

func (_c *StepFunctionsPort_ListTagsForResource_Call) Run(run func(ctx context.Context, input *sfn.ListTagsForResourceInput)) *StepFunctionsPort_ListTagsForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.ListTagsForResourceInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.ListTagsForResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_ListTagsForResource_Call) Return(listTagsForResourceOutput *sfn.ListTagsForResourceOutput, err error) *StepFunctionsPort_ListTagsForResource_Call {
	_c.Call.Return(listTagsForResourceOutput, err)
	return _c
}

func (_c *StepFunctionsPort_ListTagsForResource_Call) RunAndReturn(run func(ctx context.Context, input *sfn.ListTagsForResourceInput) (*sfn.ListTagsForResourceOutput, error)) *StepFunctionsPort_ListTagsForResource_Call {
	_c.Call.Return(run)
	return _c
}

// StartExecution provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) StartExecution(ctx context.Context, input *sfn.StartExecutionInput) (*sfn.StartExecutionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StartExecution")
	}

	var r0 *sfn.StartExecutionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.StartExecutionInput) (*sfn.StartExecutionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.StartExecutionInput) *sfn.StartExecutionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.StartExecutionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.StartExecutionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_StartExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartExecution'
type StepFunctionsPort_StartExecution_Call struct {
	*mock.Call
}

// StartExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.StartExecutionInput
func (_e *StepFunctionsPort_Expecter) StartExecution(ctx interface{}, input interface{}) *StepFunctionsPort_StartExecution_Call {
	return &StepFunctionsPort_StartExecution_Call{Call: _e.mock.On("StartExecution", ctx, input)}
}

func (_c *StepFunctionsPort_StartExecution_Call) Run(run func(ctx context.Context, input *sfn.StartExecutionInput)) *StepFunctionsPort_StartExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.StartExecutionInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.StartExecutionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_StartExecution_Call) Return(startExecutionOutput *sfn.StartExecutionOutput, err error) *StepFunctionsPort_StartExecution_Call {
	_c.Call.Return(startExecutionOutput, err)
	return _c
}

func (_c *StepFunctionsPort_StartExecution_Call) RunAndReturn(run func(ctx context.Context, input *sfn.StartExecutionInput) (*sfn.StartExecutionOutput, error)) *StepFunctionsPort_StartExecution_Call {
	_c.Call.Return(run)
	return _c
}

// StopExecution provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) StopExecution(ctx context.Context, input *sfn.StopExecutionInput) (*sfn.StopExecutionOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StopExecution")
	}

	var r0 *sfn.StopExecutionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.StopExecutionInput) (*sfn.StopExecutionOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.StopExecutionInput) *sfn.StopExecutionOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.StopExecutionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.StopExecutionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_StopExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopExecution'
type StepFunctionsPort_StopExecution_Call struct {
	*mock.Call
}

// StopExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.StopExecutionInput
func (_e *StepFunctionsPort_Expecter) StopExecution(ctx interface{}, input interface{}) *StepFunctionsPort_StopExecution_Call {
	return &StepFunctionsPort_StopExecution_Call{Call: _e.mock.On("StopExecution", ctx, input)}
}

func (_c *StepFunctionsPort_StopExecution_Call) Run(run func(ctx context.Context, input *sfn.StopExecutionInput)) *StepFunctionsPort_StopExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.StopExecutionInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.StopExecutionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_StopExecution_Call) Return(stopExecutionOutput *sfn.StopExecutionOutput, err error) *StepFunctionsPort_StopExecution_Call {
	_c.Call.Return(stopExecutionOutput, err)
	return _c
}

func (_c *StepFunctionsPort_StopExecution_Call) RunAndReturn(run func(ctx context.Context, input *sfn.StopExecutionInput) (*sfn.StopExecutionOutput, error)) *StepFunctionsPort_StopExecution_Call {
	_c.Call.Return(run)
	return _c
}

// TagResource provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) TagResource(ctx context.Context, input *sfn.TagResourceInput) (*sfn.TagResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for TagResource")
	}

	var r0 *sfn.TagResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.TagResourceInput) (*sfn.TagResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.TagResourceInput) *sfn.TagResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.TagResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.TagResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_TagResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TagResource'
type StepFunctionsPort_TagResource_Call struct {
	*mock.Call
}

// TagResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.TagResourceInput
func (_e *StepFunctionsPort_Expecter) TagResource(ctx interface{}, input interface{}) *StepFunctionsPort_TagResource_Call {
	return &StepFunctionsPort_TagResource_Call{Call: _e.mock.On("TagResource", ctx, input)}
}

func (_c *StepFunctionsPort_TagResource_Call) Run(run func(ctx context.Context, input *sfn.TagResourceInput)) *StepFunctionsPort_TagResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.TagResourceInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.TagResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_TagResource_Call) Return(tagResourceOutput *sfn.TagResourceOutput, err error) *StepFunctionsPort_TagResource_Call {
	_c.Call.Return(tagResourceOutput, err)
	return _c
}

func (_c *StepFunctionsPort_TagResource_Call) RunAndReturn(run func(ctx context.Context, input *sfn.TagResourceInput) (*sfn.TagResourceOutput, error)) *StepFunctionsPort_TagResource_Call {
	_c.Call.Return(run)
	return _c
}

// UntagResource provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) UntagResource(ctx context.Context, input *sfn.UntagResourceInput) (*sfn.UntagResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UntagResource")
	}

	var r0 *sfn.UntagResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.UntagResourceInput) (*sfn.UntagResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.UntagResourceInput) *sfn.UntagResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.UntagResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.UntagResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_UntagResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UntagResource'
type StepFunctionsPort_UntagResource_Call struct {
	*mock.Call
}

// UntagResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.UntagResourceInput
func (_e *StepFunctionsPort_Expecter) UntagResource(ctx interface{}, input interface{}) *StepFunctionsPort_UntagResource_Call {
	return &StepFunctionsPort_UntagResource_Call{Call: _e.mock.On("UntagResource", ctx, input)}
}

func (_c *StepFunctionsPort_UntagResource_Call) Run(run func(ctx context.Context, input *sfn.UntagResourceInput)) *StepFunctionsPort_UntagResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.UntagResourceInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.UntagResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_UntagResource_Call) Return(untagResourceOutput *sfn.UntagResourceOutput, err error) *StepFunctionsPort_UntagResource_Call {
	_c.Call.Return(untagResourceOutput, err)
	return _c
}

func (_c *StepFunctionsPort_UntagResource_Call) RunAndReturn(run func(ctx context.Context, input *sfn.UntagResourceInput) (*sfn.UntagResourceOutput, error)) *StepFunctionsPort_UntagResource_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStateMachine provides a mock function for the type StepFunctionsPort
func (_mock *StepFunctionsPort) UpdateStateMachine(ctx context.Context, input *sfn.UpdateStateMachineInput) (*sfn.UpdateStateMachineOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateMachine")
	}

	var r0 *sfn.UpdateStateMachineOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.UpdateStateMachineInput) (*sfn.UpdateStateMachineOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sfn.UpdateStateMachineInput) *sfn.UpdateStateMachineOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sfn.UpdateStateMachineOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sfn.UpdateStateMachineInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StepFunctionsPort_UpdateStateMachine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStateMachine'
type StepFunctionsPort_UpdateStateMachine_Call struct {
	*mock.Call
}

// UpdateStateMachine is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sfn.UpdateStateMachineInput
func (_e *StepFunctionsPort_Expecter) UpdateStateMachine(ctx interface{}, input interface{}) *StepFunctionsPort_UpdateStateMachine_Call {
	return &StepFunctionsPort_UpdateStateMachine_Call{Call: _e.mock.On("UpdateStateMachine", ctx, input)}
}

func (_c *StepFunctionsPort_UpdateStateMachine_Call) Run(run func(ctx context.Context, input *sfn.UpdateStateMachineInput)) *StepFunctionsPort_UpdateStateMachine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sfn.UpdateStateMachineInput
		if args[1] != nil {
			arg1 = args[1].(*sfn.UpdateStateMachineInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StepFunctionsPort_UpdateStateMachine_Call) Return(updateStateMachineOutput *sfn.UpdateStateMachineOutput, err error) *StepFunctionsPort_UpdateStateMachine_Call {
	_c.Call.Return(updateStateMachineOutput, err)
	return _c
}

func (_c *StepFunctionsPort_UpdateStateMachine_Call) RunAndReturn(run func(ctx context.Context, input *sfn.UpdateStateMachineInput) (*sfn.UpdateStateMachineOutput, error)) *StepFunctionsPort_UpdateStateMachine_Call {
	_c.Call.Return(run)
	return _c
}
