// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewVersionServicePort creates a new instance of VersionServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVersionServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *VersionServicePort {
	mock := &VersionServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VersionServicePort is an autogenerated mock type for the VersionServicePort type
type VersionServicePort struct {
	mock.Mock
}

type VersionServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *VersionServicePort) EXPECT() *VersionServicePort_Expecter {
	return &VersionServicePort_Expecter{mock: &_m.Mock}
}

// GetGitHubRepo provides a mock function for the type VersionServicePort
func (_mock *VersionServicePort) GetGitHubRepo() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubRepo")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// VersionServicePort_GetGitHubRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGitHubRepo'
type VersionServicePort_GetGitHubRepo_Call struct {
	*mock.Call
}

// GetGitHubRepo is a helper method to define mock.On call
func (_e *VersionServicePort_Expecter) GetGitHubRepo() *VersionServicePort_GetGitHubRepo_Call {
	return &VersionServicePort_GetGitHubRepo_Call{Call: _e.mock.On("GetGitHubRepo")}
}

func (_c *VersionServicePort_GetGitHubRepo_Call) Run(run func()) *VersionServicePort_GetGitHubRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VersionServicePort_GetGitHubRepo_Call) Return(s string) *VersionServicePort_GetGitHubRepo_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *VersionServicePort_GetGitHubRepo_Call) RunAndReturn(run func() string) *VersionServicePort_GetGitHubRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function for the type VersionServicePort
func (_mock *VersionServicePort) GetLatestVersion() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// VersionServicePort_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type VersionServicePort_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
func (_e *VersionServicePort_Expecter) GetLatestVersion() *VersionServicePort_GetLatestVersion_Call {
	return &VersionServicePort_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion")}
}

func (_c *VersionServicePort_GetLatestVersion_Call) Run(run func()) *VersionServicePort_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VersionServicePort_GetLatestVersion_Call) Return(s string, b bool) *VersionServicePort_GetLatestVersion_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *VersionServicePort_GetLatestVersion_Call) RunAndReturn(run func() (string, bool)) *VersionServicePort_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// StartScheduler provides a mock function for the type VersionServicePort
func (_mock *VersionServicePort) StartScheduler(context1 context.Context, ticker *time.Ticker) {
	_mock.Called(context1, ticker)
	return
}

// VersionServicePort_StartScheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartScheduler'
type VersionServicePort_StartScheduler_Call struct {
	*mock.Call
}

// StartScheduler is a helper method to define mock.On call
//   - context1 context.Context
//   - ticker *time.Ticker
func (_e *VersionServicePort_Expecter) StartScheduler(context1 interface{}, ticker interface{}) *VersionServicePort_StartScheduler_Call {
	return &VersionServicePort_StartScheduler_Call{Call: _e.mock.On("StartScheduler", context1, ticker)}
}

func (_c *VersionServicePort_StartScheduler_Call) Run(run func(context1 context.Context, ticker *time.Ticker)) *VersionServicePort_StartScheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *time.Ticker
		if args[1] != nil {
			arg1 = args[1].(*time.Ticker)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *VersionServicePort_StartScheduler_Call) Return() *VersionServicePort_StartScheduler_Call {
	_c.Call.Return()
	return _c
}

func (_c *VersionServicePort_StartScheduler_Call) RunAndReturn(run func(context1 context.Context, ticker *time.Ticker)) *VersionServicePort_StartScheduler_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type VersionServicePort
func (_mock *VersionServicePort) Stop() {
	_mock.Called()
	return
}

// VersionServicePort_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type VersionServicePort_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *VersionServicePort_Expecter) Stop() *VersionServicePort_Stop_Call {
	return &VersionServicePort_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *VersionServicePort_Stop_Call) Run(run func()) *VersionServicePort_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VersionServicePort_Stop_Call) Return() *VersionServicePort_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *VersionServicePort_Stop_Call) RunAndReturn(run func()) *VersionServicePort_Stop_Call {
	_c.Run(run)
	return _c
}
