package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const apiDir = "pkg/proxy/api"

func main() {

	entry := filepath.Join(apiDir, "openapi.yaml")
	out := filepath.Join(apiDir, "openapi.bundled.yaml")

	fmt.Println("Loading entry:", entry)
	spec := loadYAML(entry)

	paths := getMap(spec, "paths")
	if paths == nil {
		fmt.Fprintln(os.Stderr, "Error: no paths in spec")
		os.Exit(1)
	}

	// 1. Inline all path $refs
	fmt.Println("1. Inlining path references...")
	inlineCount := 0
	for pathKey, pathVal := range paths {
		pm, ok := pathVal.(map[string]interface{})
		if !ok {
			continue
		}
		ref, ok := pm["$ref"].(string)
		if !ok {
			continue
		}
		resolved := resolveRef(ref, apiDir)
		if resolved != nil {
			paths[pathKey] = resolved
			inlineCount++
		} else {
			fmt.Printf("  WARNING: could not resolve %s -> %s\n", pathKey, ref)
		}
	}
	fmt.Printf("  Inlined %d path refs\n", inlineCount)

	// 2. Collect all component schemas and parameters
	fmt.Println("2. Collecting component schemas...")
	allSchemas := map[string]interface{}{}
	allParams := map[string]interface{}{}

	// 2a. Common components first
	commonPath := filepath.Join(apiDir, "common", "_components.yaml")
	if _, err := os.Stat(commonPath); err == nil {
		common := loadYAML(commonPath)
		cs := getMap(common, "components", "schemas")
		for k, v := range cs {
			allSchemas[k] = v
		}
	}

	// 2b. Common parameters
	paramsPath := filepath.Join(apiDir, "common", "_parameters.yaml")
	if _, err := os.Stat(paramsPath); err == nil {
		cp := loadYAML(paramsPath)
		pm := getMap(cp, "components", "parameters")
		for k, v := range pm {
			allParams[k] = v
		}
	}

	// 2c. All service file components
	svcDir := filepath.Join(apiDir, "services")
	entries, err := os.ReadDir(svcDir)
	if err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
				continue
			}
			svcPath := filepath.Join(svcDir, e.Name())
			svc := loadYAML(svcPath)
			svcSchemas := getMap(svc, "components", "schemas")
			for k, v := range svcSchemas {
				if _, exists := allSchemas[k]; !exists {
					allSchemas[k] = v
				}
			}
			svcParams := getMap(svc, "components", "parameters")
			for k, v := range svcParams {
				if _, exists := allParams[k]; !exists {
					allParams[k] = v
				}
			}
		}
	}

	// 3. Walk inlined paths for any remaining $ref to ensure all referenced schemas are collected
	fmt.Println("3. Walking for cross-references...")
	collectRefs(paths, allSchemas, allParams, apiDir)

	// 4. Assemble bundled spec
	fmt.Println("4. Assembling bundled spec...")
	bundled := map[string]interface{}{
		"openapi": "3.0.0",
		"info":    spec["info"],
	}

	if v, ok := spec["servers"]; ok {
		bundled["servers"] = v
	}
	if v, ok := spec["tags"]; ok {
		bundled["tags"] = v
	}

	bundled["paths"] = paths

	components := map[string]interface{}{}
	if len(allSchemas) > 0 {
		components["schemas"] = allSchemas
	}
	if len(allParams) > 0 {
		components["parameters"] = allParams
	}
	if sc, ok := getMap(spec, "components")["securitySchemes"]; ok {
		components["securitySchemes"] = sc
	}
	if len(components) > 0 {
		bundled["components"] = components
	}

	// 5. Write output
	outf, err := os.Create(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output: %v\n", err)
		os.Exit(1)
	}
	defer func() {
		if err := outf.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "Error closing output: %v\n", err)
		}
	}()

	_, _ = fmt.Fprintln(outf, "# Code auto-generated by openapi-bundle; DO NOT EDIT.")

	enc := yaml.NewEncoder(outf)
	enc.SetIndent(2)
	if err := enc.Encode(bundled); err != nil {
		fmt.Fprintf(os.Stderr, "Error encoding YAML: %v\n", err)
		os.Exit(1)
	}
	if err := enc.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "Error closing YAML encoder: %v\n", err)
	}

	fmt.Printf("\nDone! %s\n", out)
	fmt.Printf("  Paths: %d\n", len(getMap(bundled, "paths")))
	fmt.Printf("  Schemas: %d\n", len(allSchemas))
	fmt.Printf("  Parameters: %d\n", len(allParams))
}

// loadYAML reads and parses a YAML file.
func loadYAML(path string) map[string]interface{} {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", path, err)
		os.Exit(1)
	}
	var result map[string]interface{}
	if err := yaml.Unmarshal(data, &result); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", path, err)
		os.Exit(1)
	}
	return result
}

// getMap navigates nested map keys safely.
func getMap(m map[string]interface{}, keys ...string) map[string]interface{} {
	current := m
	for i, k := range keys {
		v, ok := current[k]
		if !ok {
			return nil
		}
		if i == len(keys)-1 {
			if vm, ok := v.(map[string]interface{}); ok {
				return vm
			}
			return nil
		}
		if vm, ok := v.(map[string]interface{}); ok {
			current = vm
		} else {
			return nil
		}
	}
	return current
}

// resolveRef resolves a $ref string like "services/s3.yaml#/paths/~1s3~1buckets"
// relative to baseDir. Returns the resolved data or nil on failure.
func resolveRef(ref string, baseDir string) interface{} {
	parts := strings.SplitN(ref, "#", 2)
	if len(parts) != 2 {
		return nil
	}
	filePart, pointer := parts[0], parts[1]

	var data map[string]interface{}
	if filePart == "" {
		return nil
	}
	fullPath := filepath.Join(baseDir, filePart)
	data = loadYAML(fullPath)

	// Navigate the JSON pointer
	ptr := strings.TrimPrefix(pointer, "/")
	if ptr == "" {
		return data
	}
	segments := strings.Split(ptr, "/")
	current := interface{}(data)
	for _, seg := range segments {
		// Decode ~1 -> /, ~0 -> ~
		seg = strings.ReplaceAll(seg, "~1", "/")
		seg = strings.ReplaceAll(seg, "~0", "~")

		switch v := current.(type) {
		case map[string]interface{}:
			if val, ok := v[seg]; ok {
				current = val
			} else {
				return nil
			}
		default:
			return nil
		}
	}
	return current
}

// collectRefs walks data looking for $ref to components/schemas or /parameters
// and collects any not already in the maps. Recursively resolves to find nested refs.
func collectRefs(data interface{}, schemas map[string]interface{}, params map[string]interface{}, baseDir string) {
	switch v := data.(type) {
	case map[string]interface{}:
		if ref, ok := v["$ref"].(string); ok {
			if strings.Contains(ref, "/components/schemas/") {
				name := ref[strings.LastIndex(ref, "/")+1:]
				if _, exists := schemas[name]; !exists {
					if resolved := resolveRef(ref, baseDir); resolved != nil {
						schemas[name] = resolved
						collectRefs(resolved, schemas, params, baseDir)
					}
				}
			}
			if strings.Contains(ref, "/components/parameters/") {
				name := ref[strings.LastIndex(ref, "/")+1:]
				if _, exists := params[name]; !exists {
					if resolved := resolveRef(ref, baseDir); resolved != nil {
						params[name] = resolved
					}
				}
			}
		}
		for _, val := range v {
			collectRefs(val, schemas, params, baseDir)
		}
	case []interface{}:
		for _, item := range v {
			collectRefs(item, schemas, params, baseDir)
		}
	}
}
