package main

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const apiDir = "pkg/proxy/api"

func main() {
	entry := filepath.Join(apiDir, "openapi.definitions.yaml")
	out := filepath.Join(apiDir, "openapi.yaml")

	fmt.Println("Loading entry:", entry)
	spec := loadYAML(entry)

	// 1. Load all service files listed in `services:` list
	fmt.Println("1. Loading service files...")
	svcFilesRaw, ok := spec["services"]
	if !ok {
		fmt.Fprintln(os.Stderr, "Error: no 'services' list in spec")
		os.Exit(1)
	}
	svcFiles, ok := svcFilesRaw.([]any)
	if !ok {
		fmt.Fprintln(os.Stderr, "Error: 'services' must be a list")
		os.Exit(1)
	}

	allPaths := map[string]any{}
	allSchemas := map[string]any{}
	allParams := map[string]any{}

	for _, svcRaw := range svcFiles {
		svcFile, ok := svcRaw.(string)
		if !ok {
			continue
		}
		svcPath := filepath.Join(apiDir, svcFile)
		fmt.Printf("  Loading %s\n", svcFile)
		svc := loadYAML(svcPath)

		// Merge paths
		svcPaths := getMap(svc, "paths")
		for k, v := range svcPaths {
			if _, exists := allPaths[k]; !exists {
				allPaths[k] = v
			}
		}

		// Merge schemas
		svcSchemas := getMap(svc, "components", "schemas")
		for k, v := range svcSchemas {
			if _, exists := allSchemas[k]; !exists {
				allSchemas[k] = v
			}
		}

		// Merge parameters
		svcParams := getMap(svc, "components", "parameters")
		for k, v := range svcParams {
			if _, exists := allParams[k]; !exists {
				allParams[k] = v
			}
		}
	}

	// 2. Load common components
	fmt.Println("2. Loading common components...")
	commonPath := filepath.Join(apiDir, "common", "_components.yaml")
	if _, err := os.Stat(commonPath); err == nil {
		common := loadYAML(commonPath)
		cs := getMap(common, "components", "schemas")
		for k, v := range cs {
			if _, exists := allSchemas[k]; !exists {
				allSchemas[k] = v
			}
		}
	}

	// Common parameters
	paramsPath := filepath.Join(apiDir, "common", "_parameters.yaml")
	if _, err := os.Stat(paramsPath); err == nil {
		cp := loadYAML(paramsPath)
		pm := getMap(cp, "components", "parameters")
		for k, v := range pm {
			if _, exists := allParams[k]; !exists {
				allParams[k] = v
			}
		}
	}

	// 3. Assemble bundled spec
	fmt.Println("3. Assembling bundled spec...")
	bundled := map[string]any{
		"openapi": "3.0.0",
		"info":    spec["info"],
	}

	if v, ok := spec["servers"]; ok {
		bundled["servers"] = v
	}
	if v, ok := spec["tags"]; ok {
		bundled["tags"] = v
	}

	bundled["paths"] = allPaths

	components := map[string]any{}
	if len(allSchemas) > 0 {
		components["schemas"] = allSchemas
	}
	if len(allParams) > 0 {
		components["parameters"] = allParams
	}
	if sc, ok := getMap(spec, "components")["securitySchemes"]; ok {
		components["securitySchemes"] = sc
	}
	if len(components) > 0 {
		bundled["components"] = components
	}

	// 4. Write output
	outf, err := os.Create(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output: %v\n", err)
		os.Exit(1)
	}
	defer func() {
		if err := outf.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "Error closing output: %v\n", err)
		}
	}()

	_, _ = fmt.Fprintln(outf, "# Code auto-generated by openapi-bundle; DO NOT EDIT.")

	enc := yaml.NewEncoder(outf)
	enc.SetIndent(2)
	if err := enc.Encode(bundled); err != nil {
		fmt.Fprintf(os.Stderr, "Error encoding YAML: %v\n", err)
		os.Exit(1)
	}
	if err := enc.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "Error closing YAML encoder: %v\n", err)
	}

	fmt.Printf("\nDone! %s\n", out)
	fmt.Printf("  Paths: %d\n", len(getMap(bundled, "paths")))
	fmt.Printf("  Schemas: %d\n", len(allSchemas))
	fmt.Printf("  Parameters: %d\n", len(allParams))
}

// loadYAML reads and parses a YAML file.
func loadYAML(path string) map[string]any {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", path, err)
		os.Exit(1)
	}
	var result map[string]any
	if err := yaml.Unmarshal(data, &result); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", path, err)
		os.Exit(1)
	}
	return result
}

// getMap navigates nested map keys safely.
func getMap(m map[string]any, keys ...string) map[string]any {
	current := m
	for i, k := range keys {
		v, ok := current[k]
		if !ok {
			return nil
		}
		if i == len(keys)-1 {
			if vm, ok := v.(map[string]any); ok {
				return vm
			}
			return nil
		}
		if vm, ok := v.(map[string]any); ok {
			current = vm
		} else {
			return nil
		}
	}
	return current
}
